Loss and persistence geometries
PEM-Humboldt/biotablero-frontend pull request #382
Opened 2020-11-27 20:37 UTC by cazapatamar

2021-01-04 15:16 UTC, erikasv requested changes
Sorry, I didn't realize it was marked as ready for review.

2021-01-04 15:16 UTC, erikasv commented on src/Search.jsx
> +        break;
I think this case isn't being used?

2021-01-07 20:48 UTC, cazapatamar commented on src/Search.jsx
> +        break;
Fixed

2021-01-07 20:49 UTC, erikasv approved these changes

2021-01-07 20:51 UTC, merged