Feature/migrate material UI v3 v4
PEM-Humboldt/biotablero-frontend pull request #385
Opened 2021-01-26 12:57 UTC by Trjegul84

2021-01-26 13:59 UTC, cazapatamar requested changes

2021-01-26 13:59 UTC, cazapatamar commented on src/assets/main.css
> +*/
Please delete commented styles

2021-01-26 13:59 UTC, cazapatamar commented on src/commons/Selector.jsx
> +            renderInput={params => <TextField {...params} label="Escriba el nombre a buscar" placeholder="Seleccionar..." variant="standard" InputLabelProps={{ shrink: true }} />
This line is too long. Use separated lines to put the props of TextField component

2021-01-26 14:27 UTC, erikasv requested changes
Also, I think the option list from the autocomplete is too large. Would be better to show only a few options as it is right now in production. Prop `ListboxProps` must help with this.

2021-01-26 14:27 UTC, erikasv commented on src/indicator/ChipManager.jsx
> +  typography: {
Remove this property since it's empty

2021-01-26 14:34 UTC, erikasv commented
Also a couple of things missed in the first review:

- The chips in compensations are weird, did you check with Cesar this final result?
- The form to create a new project in compensation is broken (it works, but is ugly and unintelligible)
- The form to add a biome to a new project is broken (it works, but is ugly and unintelligible)
- The selections on section `Donde - Cómo` from compensations are broken (these don't work)

2021-01-27 16:19 UTC, Trjegul84 commented on src/commons/Selector.jsx
> +            renderInput={params => <TextField {...params} label="Escriba el nombre a buscar" placeholder="Seleccionar..." variant="standard" InputLabelProps={{ shrink: true }} />
TextField line was split into columns

2021-01-27 16:21 UTC, Trjegul84 commented on src/indicator/ChipManager.jsx
> +  typography: {
typography was removed.

2021-01-29 16:08 UTC, cazapatamar requested changes

2021-01-29 19:37 UTC, Trjegul84 commented on src/compensation/NewBiomeForm.jsx
>          options={biomes.map(biome => ({ ...biome, label: biome.name }))}
you are right, this was replaced as you suggest.

2021-01-29 21:09 UTC, Trjegul84 commented
> Also a couple of things missed in the first review:
> 
>     * The chips in compensations are weird, did you check with Cesar this final result?
> 
>     * The form to create a new project in compensation is broken (it works, but is ugly and unintelligible)
> 
>     * The form to add a biome to a new project is broken (it works, but is ugly and unintelligible)
> 
>     * The selections on section `Donde - Cómo` from compensations are broken (these don't work)

2021-02-01 16:24 UTC, erikasv requested changes
In the compensations selector, the autocomplete button style and on hover is different from the one in search, maybe is missing a class or something, see the screenshots

![1](https://user-images.githubusercontent.com/1734998/106486910-25574580-6480-11eb-98de-0af9f2877c6c.png)
![2](https://user-images.githubusercontent.com/1734998/106486914-25efdc00-6480-11eb-90b3-fa3175a51d69.png)

2021-02-01 16:24 UTC, erikasv commented on src/compensation/NewBiomeForm.jsx
>  /** eslint verified */
Please remove this line, it's deprecated now :sweat_smile:

2021-02-01 16:24 UTC, erikasv commented on src/compensation/NewProjectForm.jsx
>  /** eslint verified */
Please delete this line

2021-02-01 19:21 UTC, Trjegul84 commented on src/compensation/NewProjectForm.jsx
>  /** eslint verified */
Described behavior was not found, this is the current view in compensations.
![Screenshot_20210201_141833](https://user-images.githubusercontent.com/72577339/106507254-c81bbe00-6498-11eb-969a-8cac72c66dec.png)

2021-02-01 19:23 UTC, erikasv commented on src/compensation/NewProjectForm.jsx
>  /** eslint verified */
You need to add more projects to change chips for automplete

2021-02-01 19:35 UTC, Trjegul84 commented on src/compensation/NewBiomeForm.jsx
>  /** eslint verified */
Should I remove this /** eslint-env browser */ also ?

2021-02-01 19:38 UTC, erikasv commented on src/compensation/NewBiomeForm.jsx
>  /** eslint verified */
no, that allows us to use no explicitly defined variables (defined by the browser), that line should be only in `index.js` file

2021-02-01 19:41 UTC, Trjegul84 commented on src/compensation/NewBiomeForm.jsx
>  /** eslint verified */
Ok. I found 17 fifles with /** eslint verified */ then those must to be removed ?

2021-02-01 19:44 UTC, erikasv commented on src/compensation/NewBiomeForm.jsx
>  /** eslint verified */
No, the idea is to remove it from the files you modified for the issue, not to modify a lot of files only to delete that line.

2021-02-01 19:50 UTC, Trjegul84 commented on src/compensation/NewBiomeForm.jsx
>  /** eslint verified */
Ok, got it.  Line was deleted.

2021-02-01 20:37 UTC, Trjegul84 commented on src/compensation/NewProjectForm.jsx
>  /** eslint verified */
styles were modified and it looks normal now

2021-02-01 20:47 UTC, cazapatamar commented on src/compensation/NewProjectForm.jsx
>  /** eslint verified */
The autocomplete styles are fine now but when i try to load a project from this component it doesn't load.

![image](https://user-images.githubusercontent.com/19979979/106516078-901a7800-64a4-11eb-9b06-3b59c8e978e9.png)

![image](https://user-images.githubusercontent.com/19979979/106516053-87c23d00-64a4-11eb-9426-8d6d637e4c85.png)

2021-02-01 20:53 UTC, erikasv commented on src/compensation/NewProjectForm.jsx
>  /** eslint verified */
Strange, I don't remember how the list of projects is loaded and what are the conditions for a project to be valid, I would recommend to restore the tables related with projects from production into develop, maybe some project relations are broken.

Btw @Trjegul84 the line this conversation is in hasn't been deleted (src/compensation/NewProjectForm.jsx)

2021-02-01 22:21 UTC, cazapatamar commented on src/compensation/NewProjectForm.jsx
>  /** eslint verified */
> The autocomplete styles are fine now but when i try to load a project from this component it doesn't load.
> 
> ![image](https://user-images.githubusercontent.com/19979979/106516078-901a7800-64a4-11eb-9b06-3b59c8e978e9.png)
> 
> ![image](https://user-images.githubusercontent.com/19979979/106516053-87c23d00-64a4-11eb-9426-8d6d637e4c85.png)

This bug will be handled in other task and PR

2021-02-02 21:37 UTC, Trjegul84 commented on src/compensation/NewProjectForm.jsx
>  /** eslint verified */
Eslint deprecated command was deleted from NewProjectForm

2021-02-02 21:38 UTC, erikasv approved these changes

2021-02-03 15:51 UTC, cazapatamar approved these changes

2021-02-03 15:51 UTC, merged