Connectivity section1 graphs
PEM-Humboldt/biotablero-frontend pull request #412
Opened 2021-03-08 20:31 UTC by cazapatamar

2021-03-08 21:44 UTC, Trjegul84 approved these changes

2021-03-09 16:25 UTC, erikasv commented on src/pages/search/drawer/landscape/connectivity/CurrentPAConnectivity.jsx
> +              {prot}
this is a percentage right? (based on line 46) it should have the `%` symbol or a more explicit name. Or is it `Indice Prot` a percentage in general?.

I thought this value would be the total prot area :sweat_smile:

2021-03-09 16:27 UTC, erikasv requested changes
The layer is not being loaded (isn't even called)

2021-03-09 17:47 UTC, cazapatamar commented
> The layer is not being loaded (isn't even called)

The layer and interaction for this section is included in other issue. I have planned work on it in other PR

2021-03-09 20:18 UTC, merged