Connectivity section2 timeline graph
PEM-Humboldt/biotablero-frontend pull request #418
Opened 2021-03-11 12:42 UTC by Trjegul84

2021-03-11 13:34 UTC, erikasv requested changes
- When "Prot" is selected in the graph legend it turns the same color as Prot-Conn
- The legends and tooltips should say the meaning in spanish, as they are in section 1 (por example: "Protegida conectada")
- In human footprint the values were an index value, but here what are they? they should have some unit? @cazapatamar help please :see_no_evil: 
- Because of the implementation of MultilinesGraph, we can't use the darken and lighten functions to highlight the selected line, should we consider change this implementation or just keep defining 2 colors per line in matchColor? @cazapatamar

2021-03-11 13:34 UTC, erikasv commented on src/pages/search/drawer/landscape/connectivity/TimelinePAConnectivity.jsx
> +  {
What is this line for? It appears at Y=80, but has no legend.

2021-03-11 13:34 UTC, erikasv commented on src/pages/search/drawer/landscape/connectivity/TimelinePAConnectivity.jsx
> +          this.setState({ timelinePAConnectivity: prot.concat(protConn) });
I said in the backend PR, here you would process data to append the label.

Also since you are not using prot and protConn separately you don't need to destructure them and the concatenate them again, you can pass the whole result to the state or the processing function

2021-03-11 14:23 UTC, cazapatamar requested changes

2021-03-11 14:23 UTC, cazapatamar commented on src/pages/search/drawer/landscape/connectivity/TimelinePAConnectivity.jsx
> +const changeValues = [
I don't understand the name "changeValues". As it is used for markers, we would use this name instead.

2021-03-11 14:23 UTC, cazapatamar commented on src/pages/search/drawer/landscape/connectivity/TimelinePAConnectivity.jsx
> +  {
According to visualization document, there should exists a line calle "Máxima conectividad" but it's not clear if it is a fixed or calculated value. I think we should ask Jaime to clear out this point.

2021-03-11 14:24 UTC, cazapatamar commented
> * The legends and tooltips should say the meaning in spanish, as they are in section 1 (por example: "Protegida conectada")

2021-03-11 14:36 UTC, erikasv commented on src/pages/search/drawer/landscape/connectivity/TimelinePAConnectivity.jsx
> +  {
Add add a legend

2021-03-11 14:51 UTC, cazapatamar commented
> * When "Prot" is selected in the graph legend it turns the same color as Prot-Conn
> * The legends and tooltips should say the meaning in spanish, as they are in section 1 (por example: "Protegida conectada")
> * In human footprint the values were an index value, but here what are they? they should have some unit? @cazapatamar help please see_no_evil
> * Because of the implementation of MultilinesGraph, we can't use the darken and lighten functions to highlight the selected line, should we consider change this implementation or just keep defining 2 colors per line in matchColor? @cazapatamar

Sorry, i closed by mistake the PR (Already re-opened).

1. Check onClick to see what it's going on
2. I put an example of setting this labels in the back PR
3. According to data dictionary, prot and prot_conn are percentages. Actually, Jaime confirms that PROT index has to be shown as percentage in section 1. 
![image](https://user-images.githubusercontent.com/19979979/110802927-aa3a3980-824c-11eb-96d9-47e60e8d915f.png)

So, in this case it should be shown as percentage in tooltips. @Trjegul84, you can do it using a prop called "unit" and pass it to the MultiLinesGraph component with a null default value in defaultProps. Check any bars graph as a guide as there we set units as a prop.

Also, please check this line in MultiLinesGraph [()](https://github.com/PEM-Humboldt/biotablero-frontend/blob/9748164832013a19cf1720bdb6a58c9c741212d1/src/components/charts/MultiLinesGraph.jsx#L162) as it looks like to be something that only applies to graph of timeline in human footprint. Thus, we need to check all the props and settings are correctly parameterized in order to be able to reuse this component correctly without impact the current human footprint graph.

4. I'm not familiar with colors in this component but i would say suggest for now implement the simplest approach for Angela as it is her first graph.

2021-03-11 15:09 UTC, Trjegul84 commented on src/pages/search/drawer/landscape/connectivity/TimelinePAConnectivity.jsx
> +  {
Jaime said the line for "maxima conectividad" will need specialized calculations probably never be done. Therefore this line is not necessary.

2021-03-11 15:09 UTC, Trjegul84 commented on src/pages/search/drawer/landscape/connectivity/TimelinePAConnectivity.jsx
> +  }//
removed.

2021-03-11 15:12 UTC, Trjegul84 commented on src/pages/search/drawer/landscape/connectivity/TimelinePAConnectivity.jsx
> +const changeValues = [
"Maxima conectividad" wouldn't be calculated then  I will delete this changeValues.

2021-03-15 15:51 UTC, Trjegul84 commented
The percentage units and new color to highlight selected lines were added.

2021-03-15 18:25 UTC, erikasv requested changes

2021-03-15 18:25 UTC, erikasv commented on src/pages/search/drawer/landscape/connectivity/TimelinePAConnectivity.jsx
> +          this.setState({ timelinePAConnectivity: this.processData([prot, protConn]) });
Why to destructure promise response if you are sending them without changes to processData?, just send the whole variable instead of restructure it in line 28

2021-03-15 18:25 UTC, erikasv commented on src/pages/search/drawer/landscape/connectivity/TimelinePAConnectivity.jsx
> +  }//
it's still there

2021-03-15 18:25 UTC, erikasv commented on src/components/charts/MultiLinesGraph.jsx
> +            { units }
since both are variables, they can be in the same line inside an template literal

2021-03-15 18:25 UTC, erikasv commented on src/pages/search/drawer/landscape/connectivity/TimelinePAConnectivity.jsx
> +              units=" %"
don't send the units with space, adjust the chart component to add the space

2021-03-15 18:25 UTC, erikasv commented on src/utils/matchColor.js
> +    sort: ['prot', 'prot_conn'],
you're abusing the default behavior. The correct use implies to define a value for each color in the colorPalette. See values defined for each chart grouped in the same case as `timelinePAConn`.

Also check which value is being sent by the graph for the selected line, I believe is `<line_value>Sel`

Also, I suggest to define 2 different colors for selected lines, one for each line, we usually just lighten or darken the color to mark it as selected, not completely change the color

2021-03-15 20:51 UTC, Trjegul84 commented on src/pages/search/drawer/landscape/connectivity/TimelinePAConnectivity.jsx
> +          this.setState({ timelinePAConnectivity: this.processData([prot, protConn]) });
Yes, your are right. I fix it thin only one variable called "res".

2021-03-15 20:51 UTC, Trjegul84 commented on src/components/charts/MultiLinesGraph.jsx
> +            { units }
Slint gave me an error in same line but adding   ` `  the hole line was accepted.

2021-03-15 20:52 UTC, Trjegul84 commented on src/pages/search/drawer/landscape/connectivity/TimelinePAConnectivity.jsx
> +              units=" %"
I fix it in the line of MultiLinesGraph.

2021-03-15 20:52 UTC, Trjegul84 commented on src/utils/matchColor.js
> +    sort: ['prot', 'prot_conn'],
I take the HF timeline and added sort like this sort: ['prot', 'protSel', 'prot_conn', 'prot_connSel' and use the colors green, forest green, blue and deep blue.

2021-03-15 20:57 UTC, erikasv approved these changes

2021-03-15 20:59 UTC, erikasv commented
You need to merge develop into your branch to resolve conflicts

2021-03-15 21:51 UTC, erikasv requested changes

2021-03-15 21:51 UTC, erikasv commented on src/utils/restAPI.js
> +   static requestCurrentPAConnectivityBySE(areaType, areaId, seType) {
This merge is bad, you're breaking up develop

2021-03-15 21:51 UTC, erikasv commented on src/utils/restAPI.js
> +   static requestCurrentPAConnectivityBySE(areaType, areaId, seType) {
I don't know what you did, but you pushed again all commits. You need to restore the function deleted in the merge.

2021-03-15 22:03 UTC, erikasv approved these changes

2021-03-15 22:05 UTC, Trjegul84 reviewed
resAPI.js was restore.

2021-03-15 22:07 UTC, Trjegul84 commented
I cant perform the step 2:

git push origin develop 
Enumerando objetos: 1, listo.
Contando objetos: 100% (1/1), listo.
Escribiendo objetos: 100% (1/1), 250 bytes | 250.00 KiB/s, listo.
Total 1 (delta 0), reusado 0 (delta 0), pack-reusado 0
remote: error: GH006: Protected branch update failed for refs/heads/develop.
remote: error: At least 1 approving review is required by reviewers with write access.
To https://github.com/PEM-Humboldt/biotablero-frontend.git
 ! [remote rejected]   develop -> develop (protected branch hook declined)
error: falló el push de algunas referencias a 'https://github.com/PEM-Humboldt/biotablero-frontend.git'

2021-03-15 22:13 UTC, erikasv commented
why are you trying to push to develop?, it can't be done.

You first made the merge from develop into your branch, but I don't know what else you did that you end up with all the commits from your branch duplicated. Then you push another commit restoring the function deleted in the merge.

What else are you trying to do?

2021-03-15 22:18 UTC, Trjegul84 commented
Just the step 1, and step 2. But merge failed. I followed the instructions git returned:
Auto-fusionando src/utils/restAPI.js
CONFLICTO (contenido): Conflicto de fusión en src/utils/restAPI.js
error: no se pudo aplicar 4e66f55e...  Create requestTimelinePAConnectivity function to get timeline data
Resolve all conflicts manually, mark them as resolved with
**"git add/rm <conflicted_files>", then run "git rebase --continue".**
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
No se pudo aplicar 4e66f55e... Create requestTimelinePAConnectivity function to get timeline data

then 
git restore --staged src/utils/restAPI.js
git rebase --continue

git status
En la rama develop
Tu rama está adelantada a 'origin/develop' por 7 commits.
  (usa "git push" para publicar tus commits locales)

nada para hacer commit, el árbol de trabajo está limpio
then git push that failed !

2021-03-15 22:26 UTC, erikasv commented
I don't know were you get those steps from. 

But I don't think this has effect on a merge:
> git restore --staged src/utils/restAPI.js

Also, this command is for a rebase
> git rebase --continue

 And again, I don't understand what are you trying to do in develop, you can't push directly to develop, it can only be made through PR. That's why I told you to merge develop into your branch, and you already did it (also duplicating your old commits)

2021-03-15 22:33 UTC, Trjegul84 commented
I am sorry, It was my mistake  trying to fix the conflicts and later the step1 and step 2 command to merge it via command line.
git checkout develop
git merge --no-ff feature/mockTimelineConnectivity
git push origin develop

2021-03-16 19:32 UTC, cazapatamar approved these changes

2021-03-16 19:39 UTC, merged

2021-03-16 20:11 UTC, Trjegul84 commented
Se arreglaron los errores y conflictos. 
Se escogieron dos colores (verdes y azules) por cada línea.