display geometry in connectivity section 2
PEM-Humboldt/biotablero-frontend pull request #425
Opened 2021-03-16 20:59 UTC by Trjegul84

Only call add timelineConn cases to apply same functions of section 1 in section 2 also same colors.

2021-03-16 23:12 UTC, erikasv requested changes

2021-03-16 23:12 UTC, erikasv commented on src/pages/Search.jsx
> +      case 'timelinePAConn':
You need to make a separated case because of the layer name

2021-03-16 23:13 UTC, erikasv commented
@cazapatamar can you check the geofence layer is being shown? In my local it's showing only the dpc layer in both cases (current and timeline)

2021-03-16 23:47 UTC, cazapatamar commented
> @cazapatamar can you check the geofence layer is being shown? In my local it's showing only the dpc layer in both cases (current and timeline)

In my local i see both layers

![image](https://user-images.githubusercontent.com/19979979/111394078-f8ee3600-8687-11eb-8407-3254fc2362e7.png)

2021-03-17 15:19 UTC, Trjegul84 commented
Using develop branch in my local I see both layers are displayed in current and timeline. I thought this was due to mockup data is not linked with area_id. 
![Screenshot_20210129_105602](https://user-images.githubusercontent.com/72577339/111491799-27acf080-870a-11eb-8700-f88929429b0e.png)

2021-03-17 21:27 UTC, erikasv requested changes

2021-03-17 21:27 UTC, erikasv commented on src/pages/Search.jsx
> +          id: layerType,
Use `currentPAConn` as the active layer id and also as the `layerKey`, so you don't load twice the same layer.

See the case for hf timeline for reference

2021-03-17 21:53 UTC, Trjegul84 commented on src/pages/Search.jsx
> +          id: layerType,
Ok. Changed. It is better solution than duplicate the code.

2021-03-17 22:05 UTC, erikasv requested changes

2021-03-17 22:05 UTC, erikasv commented on src/pages/Search.jsx
> +          id: 'layerType',
You just set the new active layer id to the string "layerType", it should be `'currentPAConn'` as it's reusing the layer for currentPAConn

2021-03-17 22:05 UTC, erikasv commented on src/pages/Search.jsx
> +        layerStyle = this.featureStyle({ type: 'currentPAConn' });
you must send `fKey` or it won't work, right now it works because the layer loads too fast, but if you change accordion tab before the layer for the first section is loaded, this won't load correctly

2021-03-18 14:44 UTC, erikasv approved these changes

2021-03-18 14:44 UTC, merged