Connectivity section1 visual adjustments
PEM-Humboldt/biotablero-frontend pull request #441
Opened 2021-04-13 19:18 UTC by cazapatamar

2021-04-13 22:41 UTC, erikasv requested changes
The "loading" modal for the dpc layer is missing, it takes some time to show up.

2021-04-15 12:36 UTC, Trjegul84 approved these changes

2021-04-15 15:25 UTC, erikasv commented
Also you should connect this PR to the issue in the back

2021-04-15 21:49 UTC, erikasv approved these changes

2021-04-16 20:29 UTC, merged