New adjustments in connectivity
PEM-Humboldt/biotablero-frontend pull request #460
Opened 2021-05-03 21:58 UTC by cazapatamar

2021-05-03 23:27 UTC, Trjegul84 requested changes
I've highlight in red some values that are not completely visible, I think the numbers are to long to be there and not placed well. Are those necessary at the left of the bars?

![Cifras-NoVisibles](https://user-images.githubusercontent.com/72577339/116945308-f1391f80-ac3c-11eb-8c4b-eaa8d7aad293.png)

2021-05-04 14:52 UTC, cazapatamar commented
> I've highlight in red some values that are not completely visible, I think the numbers are to long to be there and not placed well. Are those necessary at the left of the bars?
> 
> ![Cifras-NoVisibles](https://user-images.githubusercontent.com/72577339/116945308-f1391f80-ac3c-11eb-8c4b-eaa8d7aad293.png)

It seems to be a problem with nivo upgrade you did in the other PR. Try to delete node_modules, install dependencies again been on this branch and test again. In my local env i don't see labels at Y-axis as it should be.

![image](https://user-images.githubusercontent.com/19979979/117022766-1cb01e80-acbe-11eb-818e-aef8134b5336.png)

if indeed it is issue related to nivo upgrade, please solve it in the PR #459

2021-05-04 14:54 UTC, Trjegul84 commented
Ok, thanks, I will check again.

2021-05-04 14:58 UTC, erikasv commented
@cazapatamar are you suggesting we should merge this branch first?, because if that problem happens because of the nivo upgrade it equally has to be solved

2021-05-04 15:04 UTC, cazapatamar commented
> @cazapatamar are you suggesting we should merge this branch first?, because if that problem happens because of the nivo upgrade it equally has to be solved

I mean, first solve the issue but in the other PR where we are upgrading nivo and not here. What do you think? @erikasv

2021-05-04 15:05 UTC, erikasv commented
> I mean, first solve the issue but in the other PR where we are upgrading nivo and not here. What do you think? @erikasv

Yeah agree, I just saw your comment in the other PR. I just was worried the problem wouldn't be solved.

2021-05-04 16:40 UTC, cazapatamar commented
> > I mean, first solve the issue but in the other PR where we are upgrading nivo and not here. What do you think? @erikasv
> 
> Yeah agree, I just saw your comment in the other PR. I just was worried the problem wouldn't be solved.

@erikasv After checking with @Trjegul84 we realize the issue is not associated to nivo upgrade but to an error inside the component as i was setting the axisLeft prop instead of being null. It was already fixed in the last commit.

2021-05-04 18:10 UTC, erikasv commented on src/components/charts/GraphLoader.jsx
> -          labelY={labelY}
Wouldn't this affect the Loss and persistence graph?

2021-05-04 18:11 UTC, erikasv commented on src/components/charts/MultiSmallSingleBarGraph.jsx
> -      labelY,
Same that previous comment, this wouldn't affect loss and persistence section?

2021-05-04 18:14 UTC, cazapatamar commented on src/components/charts/GraphLoader.jsx
> -          labelY={labelY}
No, the component is different for Loss and persistence graph whose name is MultiSmallBarStackGraph

2021-05-04 18:14 UTC, cazapatamar commented on src/components/charts/MultiSmallSingleBarGraph.jsx
> -      labelY,
Same last comment

2021-05-04 18:16 UTC, Trjegul84 approved these changes

2021-05-04 19:36 UTC, erikasv approved these changes

2021-05-04 20:39 UTC, merged