Feature/download csv files
PEM-Humboldt/biotablero-frontend pull request #477
Opened 2021-05-25 22:15 UTC by Trjegul84

NOTES:
- You must add the library with `yarn add react-json-to-csv`
- In this task the examples of CSV Download Button performed where: **Biomes** and **currentPAConnectivity**.
- File Names of CSV downloaded by user must be standardized. I need help to find out the way of name every file according the area that has been selected. (i.e Biotablero_Biomas_CAR_Quindio.csv)
- In the other tabs, select a place for the download button and later the styles will be fixed.

2021-05-25 22:31 UTC, erikasv commented
`yarn add` is only to add a new dependency, the command adds it to the package.json file. I our case we must install new dependencies running `yarn install`

2021-05-25 22:36 UTC, erikasv commented
For the name, I think we should name it with the `area_type` and `area_id`, these values are already on the URL, so it wouldn't add something strange for the user, for example:  "biotablero_biomas_ea_CRQ.csv"

I think that the word "biotablero" makes it too long for the file name, maybe it's better just "biomas_ea_CRQ.csv", but I also think that would be good to check with Jaime if this name is important, in case we need to add the labels to the context.

2021-05-25 22:43 UTC, erikasv requested changes

2021-05-25 22:43 UTC, erikasv commented on src/components/DownloadCSV.jsx
> +import SearchContext from 'pages/search/SearchContext';
This import goes at the end and separated by a blank line. The order is: 

1. Language imports
2. blank line
3. Libraries imports
4. blank line
5. Our modules imports
6. blank lines

2021-05-25 22:43 UTC, erikasv commented on src/components/DownloadCSV.jsx
> +import SearchContext from 'pages/search/SearchContext';
And I prefer sort the imports alphabetically (but we have never made a agreement with that :P)

2021-05-25 22:43 UTC, erikasv commented on src/components/DownloadCSV.jsx
> +          buttonlabel: 'Descargar Datos',
This shouldn't be an state, it could be one of two things:

1. Since the state is never changed, it could be a common variable in a functional component.
2. Or it could be a prop allowing it to be customizable

2021-05-25 22:43 UTC, erikasv commented on src/components/DownloadCSV.jsx
> +DownloadCSV.contextType = SearchContext;
You're not using context

2021-05-26 14:26 UTC, Trjegul84 commented
> `yarn add` is only to add a new dependency, the command adds it to the package.json file. I our case we must install new dependencies running `yarn install`

Please explain me, I don't understand well. When I wrote the component if yarn install is performed it did nothing. Then I perform the command and it works. How is the way of adding this new libraries?.

2021-05-26 14:27 UTC, Trjegul84 commented
> For the name, I think we should name it with the `area_type` and `area_id`, these values are already on the URL, so it wouldn't add something strange for the user, for example: "biotablero_biomas_ea_CRQ.csv"
> 
> I think that the word "biotablero" makes it too long for the file name, maybe it's better just "biomas_ea_CRQ.csv", but I also think that would be good to check with Jaime if this name is important, in case we need to add the labels to the context.

Please, help me. I don't know how to do it. If I get the context and set  it with `${areaId}_${geofenceId}` the result is like states_63 not the Spanish names.

2021-05-26 14:27 UTC, Trjegul84 commented on src/components/DownloadCSV.jsx
> +import SearchContext from 'pages/search/SearchContext';
Since I dont find this rules in other components, for example, some add react at the beging others at the end. Then I took the example of Forest.jsx.

2021-05-26 14:28 UTC, Trjegul84 commented on src/components/DownloadCSV.jsx
> +          buttonlabel: 'Descargar Datos',
Component now is functional component.

2021-05-26 14:28 UTC, Trjegul84 commented on src/components/DownloadCSV.jsx
> +DownloadCSV.contextType = SearchContext;
I've delete it.

2021-05-26 15:00 UTC, erikasv commented on src/components/DownloadCSV.jsx
> +import SearchContext from 'pages/search/SearchContext';
Yeah, as I said we haven't agreed on the sort thing, but actually the Forest component has it right with the separation, in our case react and prop-types are considered "language" imports.

2021-05-26 15:57 UTC, cazapatamar commented
> For the name, I think we should name it with the `area_type` and `area_id`, these values are already on the URL, so it wouldn't add something strange for the user, for example: "biotablero_biomas_ea_CRQ.csv"
> 
> I think that the word "biotablero" makes it too long for the file name, maybe it's better just "biomas_ea_CRQ.csv", but I also think that would be good to check with Jaime if this name is important, in case we need to add the labels to the context.

Agree with @erikasv we should make it simple. As we already use areaType and areaId at URL i think the file name can be composed by these parameters.

2021-05-26 16:01 UTC, cazapatamar commented
> > `yarn add` is only to add a new dependency, the command adds it to the package.json file. I our case we must install new dependencies running `yarn install`
> 
> Please explain me, I don't understand well. When I wrote the component if yarn install is performed it did nothing. Then I perform the command and it works. How is the way of adding this new libraries?.

I usually install the new dependency with `yarn install <DEPENDENCY>` and that's all.

2021-05-26 16:04 UTC, cazapatamar commented
> > For the name, I think we should name it with the `area_type` and `area_id`, these values are already on the URL, so it wouldn't add something strange for the user, for example: "biotablero_biomas_ea_CRQ.csv"
> > I think that the word "biotablero" makes it too long for the file name, maybe it's better just "biomas_ea_CRQ.csv", but I also think that would be good to check with Jaime if this name is important, in case we need to add the labels to the context.
> 
> Please, help me. I don't know how to do it. If I get the context and set it with `${areaId}_${geofenceId}` the result is like states_63 not the Spanish names.

Yes, it's right. 'states' is the areaType and 63 is the areaId. According to @erikasv suggestion and i agree, we should not use the area name. First, because it is not in the context. Second, the names could be too long in some cases.

2021-05-26 16:05 UTC, Trjegul84 commented
> > > `yarn add` is only to add a new dependency, the command adds it to the package.json file. I our case we must install new dependencies running `yarn install`
> > 
> > 
> > Please explain me, I don't understand well. When I wrote the component if yarn install is performed it did nothing. Then I perform the command and it works. How is the way of adding this new libraries?.
> 
> I usually install the new dependency with `yarn install <DEPENDENCY>` and that's all.

Yes it should be easy but for me this message is returned when I do that for any library:
```
Unknown Syntax Error: Extraneous positional argument ("anylibrarywhatever").

$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--skip-builds]
```

2021-05-26 16:14 UTC, erikasv commented
> ...
> Yes it should be easy but for me this message is returned when I do that for any library:

@Trjegul84 @cazapatamar please read the first part of this documentation: https://classic.yarnpkg.com/en/docs/cli/install/

`yarn install` by itself is to install project's dependencies.

The command @cazapatamar mentions it's to install a missing the dependency in your codebase, that means we could run `yarn install react-json-to-csv` to install that specific dependency in our clones.

`yarn add` is to add a new dependency to the project's package.json (and obviously install it in your copy) : https://classic.yarnpkg.com/en/docs/cli/add

2021-05-26 16:16 UTC, erikasv commented
> Please, help me. I don't know how to do it. If I get the context and set it with `${areaId}_${geofenceId}` the result is like states_63 not the Spanish names.

That's exactly my point, not to use names but ids, we should agree in one name template and then ask Jaime how important is this name (explaining that names are not currently accessible from the button)

2021-05-26 16:19 UTC, erikasv commented
I think this could be merge now, and after we decide the name this afternoon, we can change it with the implementation of the rest of the buttond. @cazapatamar what do you think?

2021-05-26 16:36 UTC, cazapatamar commented
Agarre!

2021-05-26 16:37 UTC, cazapatamar commented
> I think this could be merge now, and after we decide the name this afternoon, we can change it with the implementation of the rest of the buttons. @cazapatamar what do you think?

Agree!

2021-05-26 16:38 UTC, erikasv approved these changes

2021-05-26 16:40 UTC, merged