Release/1.7.0
PEM-Humboldt/biotablero-frontend pull request #488
Opened 2021-06-01 20:16 UTC by Trjegul84

2021-06-02 02:08 UTC, erikasv requested changes

2021-06-02 13:44 UTC, Trjegul84 commented on src/components/charts/LargeBarStackGraph.jsx
> +   * @returns {func} tooltip for component
I've also found getToolTip returning func in SmallBarStackGraph. Should I change both to `@returns {object}` ?

2021-06-02 14:20 UTC, erikasv commented on src/components/charts/LargeBarStackGraph.jsx
> +   * @returns {func} tooltip for component
yes please

2021-06-02 14:54 UTC, Trjegul84 commented on src/components/charts/LargeBarStackGraph.jsx
> +   * @returns {func} tooltip for component
Done in the  feature/fixIndentation PR

2021-06-02 14:56 UTC, Trjegul84 commented on src/components/charts/LargeBarStackGraph.jsx
> +    /**
Fixed in the PR of feature/fixIndentation branch

2021-06-02 15:03 UTC, erikasv approved these changes

2021-06-02 19:24 UTC, alegnaaived approved these changes

2021-06-04 17:11 UTC, cazapatamar approved these changes

2021-06-08 12:23 UTC, merged