Feature/indicators package
PEM-Humboldt/biotablero-frontend pull request #520
Opened 2021-09-14 05:02 UTC by alegnaaived

2021-09-14 20:53 UTC, erikasv requested changes
Important note:
**A lot of commits aren't in the message format we agreed on the workflow document.**

Other adjustments
* The package must be able to run independently, at this moment when I run `yarn workspace indicators run dev` throws this error: `Error: No transformers found for packages/indicators/src/icons/link.svg`
* When I try to run the package inside BioTablero it throws this error when it detects changes: `[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)`
* We agreed to follow the [fractal structure](https://hackernoon.com/fractal-a-react-app-structure-for-infinite-scale-4dab943092af), so `CardManager` should be inside another folder named `app`. Inside this folder also should be `data` and `cardManager`
* When I ran `yarn install` the `yarn.lock` file was updated, so it means it's outdated in the branch
* All the code related with indicators in the main project should be deleted.
* `Indicators.jsx` must be renamed to `Indicator.jsx`

2021-09-14 20:53 UTC, erikasv commented on packages/indicators/src/cardManager/Card.jsx
> +import LinkIcon from '../icons/link.svg';
I want to know @Trjegul84 and @cazapatamar opinion on this, I didn't like to import svg directly in the polygon functionality to be able to control size and color as props, see [PolygonIcon](https://github.com/PEM-Humboldt/biotablero-frontend/blob/develop/src/pages/search/selector/PolygonIcon.jsx) as an example. Should we keep this strategy for all custom svg icons?

2021-09-14 20:53 UTC, erikasv commented on packages/indicators/src/CardManager.jsx
> +        action="./Indicadores"
instead of `action` you should use `url` or `href` since it actually is a link

2021-09-14 20:53 UTC, erikasv commented on packages/indicators/src/icons/link.svg
> +</svg>
new line missing

2021-09-14 20:53 UTC, erikasv commented on packages/indicators/src/CardManager.jsx
> +        action="./Indicadores"
And it's not static

2021-09-14 20:53 UTC, erikasv commented on packages/indicators/src/data/selectorData.js
> +    id: '1',
missing link in data

2021-09-14 21:38 UTC, alegnaaived commented
Changes done in commits messages according to [workflow document](https://docs.google.com/document/d/1TGc0AX6aIhxKNArgszvij6KRoHZ0uYSzuTMfRvDDO-E/edit#)

> Important note:
> **A lot of commits aren't in the message format we agreed on the workflow document.**
> 
Other adjustments (In progress)

2021-09-15 21:19 UTC, erikasv commented on src/main.css
> +.Indicadores {
My mistake, the classes are seted dynamically

2021-09-16 15:04 UTC, erikasv commented
@alegnaaived Why did you renamed the package?

2021-09-16 15:55 UTC, erikasv requested changes
1. I don't understand why you changed the package name, the instruction in the previous review was to rename the component (in pages) from the main project, but the package is independent. The change makes terribly difficult to identify the changes you introduced. Although if every one agree it's better to keep it singular, update the documentation so it can be a reliable example.

2. When the console is open I noticed a strange behavior, then added more test data and it replicated:
![1](https://user-images.githubusercontent.com/1734998/133643550-598d5441-41e3-45e6-a161-b8bed145a848.png)

2021-09-16 15:55 UTC, erikasv commented on packages/indicator/src/App.jsx
> +                (Prueba de apertura del menú)
This button isn't to close the menu, is to clear all applied filters. You can just delete it because it's out of scope for this issue

2021-09-16 15:55 UTC, erikasv commented on packages/indicator/src/app/CardManager.jsx
> +    </div>
It looks funny, maybe works better if you put them inside same div?
![1](https://user-images.githubusercontent.com/1734998/133639869-1f3b71dd-6512-4658-aba3-cc195384c8aa.png)

Also, check SaveAlt or SystemUpdateAlt icons, they look more similar to the one Cesar put in mockups, check with him which one fits better

2021-09-16 15:55 UTC, erikasv commented on packages/indicator/src/app/CardManager.jsx
> +    </div>
Also I think this section fits better in the App component, as you had it before, so CardManager only care about organizing cards. But if you want to keep it here, move the cards data extraction to this component, instead of a prop

2021-09-16 15:55 UTC, erikasv commented on packages/indicator/src/app/cardManager/Card.jsx
> +    <h2>{period}</h2>
This prop is optional, you should render it only if it's present (to avoid posible spaces created by margin and padding later)

2021-09-16 15:55 UTC, erikasv commented on packages/indicator/src/app/CardManager.jsx
> +      <GetAppOutlinedIcon color="#e84a5f" />
![1](https://user-images.githubusercontent.com/1734998/133642374-ceeff84b-e158-46b8-86da-100b4d1748f9.png)

2021-09-16 15:55 UTC, erikasv commented on packages/indicator/src/app/data/selectorData.js
> +  },
What is the purpose of this case?

2021-09-16 15:55 UTC, erikasv commented on packages/indicator/package.json
> +    "rollup-plugin-react-svg": "^3.0.3"
What is this dependency for? I removed it and it works fine

2021-09-16 20:14 UTC, alegnaaived commented on packages/indicator/src/app/data/selectorData.js
> +  },
Showing default styles, but I can remove it

2021-09-17 15:21 UTC, cazapatamar requested changes

2021-09-17 15:21 UTC, cazapatamar commented on packages/indicators/src/app/data/selectorData.js
> +  },
Also agree with deleting this case

2021-09-17 15:46 UTC, cazapatamar requested changes

2021-09-17 15:46 UTC, cazapatamar commented on packages/indicators/src/App.jsx
> +          )}
I would delete this div as it is only a test. According to the task scope you should only let a side empty panel, where there will be filters.

2021-09-17 15:50 UTC, cazapatamar commented
> @alegnaaived Why did you renamed the package?

I think `Indicators` was a suitable name to the package. I also didn't understand this change.

2021-09-17 19:34 UTC, alegnaaived commented
> @alegnaaived Why did you renamed the package?

Due to it was a misunderstanding, I changed it again.

2021-09-20 15:11 UTC, erikasv requested changes

2021-09-20 15:11 UTC, erikasv commented on packages/indicators/src/app/CardManager.jsx
> +  cardsData: PropTypes.arrayOf(
instead of redefining the shape set `arrayOf` to be the Card proptypes, in that component they are well defined

2021-09-21 13:04 UTC, alegnaaived commented on packages/indicators/src/app/cardManager/Card.jsx
> +import LinkIcon from './card/URLIcon';
Done

2021-09-21 13:05 UTC, alegnaaived commented on packages/indicators/src/app/cardManager/Card.jsx
> +import LinkIcon from './card/URLIcon';
Done

2021-09-23 20:59 UTC, erikasv requested changes
Also run `format` script in the package

2021-09-23 20:59 UTC, erikasv commented on packages/indicators/src/App.jsx
> +import DownloadIcon from './app/cardManager/card/DownloadIcon';
`DownloadIcon` should be in `app` folder (not `card`). Please review the fractal post.

2021-09-23 20:59 UTC, erikasv commented on packages/indicators/src/App.jsx
> +import OpenIcon from './app/cardManager/card/OpenIcon';
`OpenIcon` should be in a new folder `src/components`

2021-09-23 20:59 UTC, erikasv commented on packages/indicators/src/App.jsx
> +import CloseIcon from './app/cardManager/card/CloseIcon';
This is also in the wrong location

2021-09-23 20:59 UTC, erikasv commented on packages/indicators/src/app/CardManager.jsx
> +  cardsData: PropTypes.arrayOf(Card).isRequired,
I think the correct way is to reference the Card propTypes, beacuse you are nor receiving the component itself, but its props. [See this](https://stackoverflow.com/questions/59283221/how-to-define-proptypes-for-a-component-that-only-passes-props-to-a-child/59283558#59283558).

But I just noticed you have 2 differences: `key` and `indicator` are Card props, but in this component are `id` and `title`, so you could change some of the props to make it easier.

2021-09-27 13:23 UTC, erikasv requested changes

2021-09-27 13:23 UTC, erikasv commented on packages/indicators/src/App.jsx
> +import CloseIcon from './components/CloseIcon';
Why did you put this inside `components` folder? I only see it used by app.

2021-09-27 13:23 UTC, erikasv commented on packages/indicators/src/app/CardManager.jsx
> +  ...Card.propTypes,
CardManager receives one prop named cardsData which is an array of objects. Not as many props as the Card component

2021-09-27 20:24 UTC, erikasv approved these changes

2021-09-27 20:36 UTC, cazapatamar approved these changes

2021-09-27 20:53 UTC, merged