Feature/gaps adjustments
PEM-Humboldt/biotablero-frontend pull request #574
Opened 2021-11-19 19:23 UTC by Trjegul84

2021-11-19 19:54 UTC, erikasv requested changes

2021-11-19 19:54 UTC, erikasv commented on src/pages/search/drawer/species/richness/NumberOfSpecies.jsx
> +                  <>
This is not necessary, put only the div

2021-11-19 19:54 UTC, erikasv commented on src/pages/search/drawer/species/richness/NumberOfSpecies.jsx
> +                       Add I2D link when it's ready (import mappointlink and mappointlink2 images)
this indentation is wrong

2021-11-19 19:54 UTC, erikasv commented on src/pages/search/drawer/species/richness/NumberOfSpecies.jsx
> +                    )}
this indentation is also wrong

2021-11-19 19:54 UTC, erikasv commented on src/pages/search/drawer/species/richness/SpeciesRecordsGaps.jsx
> +            Los vacíos en el área de consulta son mayores o menores que los de la región biótica
This applies for min and max values, maybe we should express that in the message

2021-11-22 22:12 UTC, Trjegul84 commented on src/pages/search/drawer/species/richness/SpeciesRecordsGaps.jsx
> +            Los vacíos en el área de consulta son mayores o menores que los de la región biótica
New message is just as Jaime said.

2021-11-22 22:12 UTC, Trjegul84 commented on src/pages/search/drawer/species/richness/NumberOfSpecies.jsx
> +                    )}
deleted

2021-11-23 14:11 UTC, erikasv approved these changes

2021-11-23 14:31 UTC, merged