Coverage update data
PEM-Humboldt/biotablero-frontend pull request #617
Opened 2022-03-10 16:54 UTC by cazapatamar

New colors already validated with Cesar

This PR depends on branch in the backend which name is `[feature/coverageColors](https://github.com/PEM-Humboldt/biotablero-backend/tree/feature/coverageColors)`

2022-03-10 17:55 UTC, erikasv requested changes

2022-03-10 17:55 UTC, erikasv commented on src/pages/Search.jsx
> +
I don't like this object here, it can vary from section to section the value of the "default opacity", it's better to have the value set for each section or since it's needed from various functions, save it in the rasterUrls state.

I think we could always assume the highlighted raster section will have opacity 1.

2022-03-10 17:55 UTC, erikasv commented on src/pages/Search.jsx
> +  highlightRaster = (layerName) => {
According to the comparison, this param is in reality the layer id, not name

2022-03-10 21:09 UTC, Trjegul84 submitted a review, later dismissed

2022-03-10 23:22 UTC, cazapatamar commented on src/pages/Search.jsx
> +  highlightRaster = (layerName) => {
Done

2022-03-10 23:26 UTC, cazapatamar commented on src/pages/Search.jsx
> +
Add default opacity to `activeLayer` state and delete `rasterOpacity` object that was out of the class. I think this solution allows to set a different opacity to each case at `setSectionLayers` function.

2022-03-11 13:05 UTC, erikasv requested changes

2022-03-11 13:05 UTC, erikasv commented on src/pages/Search.jsx
> +    newActiveLayer.defaultOpacity = 1;
Add `defaultOpacity` key to the object declared in the previous line

2022-03-11 14:05 UTC, erikasv approved these changes

2022-03-11 14:18 UTC, merged