Strategic ecosystem update data
PEM-Humboldt/biotablero-frontend pull request #632
Opened 2022-04-07 00:30 UTC by cazapatamar

2022-04-07 17:18 UTC, erikasv commented on src/pages/Search.jsx
> +      newActiveLayer.name = `Número de especies - ${SELabel(seType)}`;
¿Número de especies?

2022-04-07 17:20 UTC, erikasv commented on src/pages/search/drawer/StrategicEcosystems.jsx
> +      SETotalArea: 0,
Good call, way better names

2022-04-07 17:49 UTC, cazapatamar commented on src/pages/Search.jsx
> +      newActiveLayer.name = `Número de especies - ${SELabel(seType)}`;
Fixed!

2022-04-07 18:06 UTC, erikasv requested changes
Great job organizing the components' variables and props. :clap: 

You're missing the handling of the case when there is an empty layer for just one or two coverage types (not all of them), check the case of arauca for example (id: 81) the area for coverage `S` is so small that the layer is empty and the front is showing the `CAPA NO DISPONBLE` error.

2022-04-07 19:54 UTC, Trjegul84 reviewed
Something happen when you first expand information in Páramo and then if you expand another SE for example Tropical Dry forest it  sends an error like: `TypeError: np is undefined`

![Screenshot_20220407_145352](https://user-images.githubusercontent.com/72577339/162285280-7c0d0df2-b9d6-4f17-9cf3-82bf0e607d99.png)

Take a look of this case:
area_type=ea&area_id=CORPOCHIVOR

2022-04-07 20:31 UTC, cazapatamar commented
> Something happen when you first expand information in Páramo and then if you expand another SE for example Tropical Dry forest it sends an error like: `TypeError: np is undefined`
> 
> ![Screenshot_20220407_145352](https://user-images.githubusercontent.com/72577339/162285280-7c0d0df2-b9d6-4f17-9cf3-82bf0e607d99.png)
> 
> Take a look of this case: area_type=ea&area_id=CORPOCHIVOR

This bug is actually in develop, it seems it is related to distribution of protected areas in selected SE. Apparently we are missing to set the section in the bar graph asociated to category `No protected` (Grey color) after adjustments over protected area endpoints.

I think it is better to solve it in another task. What do you think? @erikasv @Trjegul84 

![imagen](https://user-images.githubusercontent.com/19979979/162290757-0507b46d-df4e-4b24-b392-c8e68dae32ef.png)

2022-04-07 20:47 UTC, Trjegul84 commented
Ok, I agree it could be handled in a fix bug task.

2022-04-07 20:52 UTC, cazapatamar commented
> Great job organizing the components' variables and props. clap
> 
> You're missing the handling of the case when there is an empty layer for just one or two coverage types (not all of them), check the case of arauca for example (id: 81) the area for coverage `S` is so small that the layer is empty and the front is showing the `CAPA NO DISPONBLE` error.

Solved!

2022-04-07 23:03 UTC, erikasv commented
> I think it is better to solve it in another task. What do you think? @erikasv @Trjegul84

Sorry for the delay, yeah, this should be solved with the new calculation of percentages in protected areas, right now this only happens with environmental authorities because of the issue with the new query, after we solve the issue backend-294 it will happen with all area types.

2022-04-07 23:20 UTC, erikasv commented
Sorry @cazapatamar, the error Angela mentioned also happens in states and in that case is not related with the changes done in the protected areas query.

The problem is related when there are no protected areas at all in the strategic ecosystem, so, although the logic of that function (`setPAValues`) will need to be changed, it is better to add that control for when there are no protected areas. (just add that condition to the firs if :P)

2022-04-07 23:35 UTC, erikasv commented on src/pages/Search.jsx
> +    const isMultipleLayers = rasterLayerIds.length > 1;
With this solution you can't know if all the layers failed, it think it would be better to change the condition of this `if (rasterLayers.includes('canceled'))` to return the error only if all rasters failed

2022-04-08 12:13 UTC, Trjegul84 commented
@cazapatamar @erikasv  Please tell me if the following behavior is desirable: If you expand any strategic ecosystem then you can no longer back to see the Coverage. I mean you can't return to Coverage bar and look its layer because click action is kind of disabled. In the same page the only way to see again the Coverage Layer is refreshing it.

2022-04-08 15:08 UTC, cazapatamar commented
> Something happen when you first expand information in Páramo and then if you expand another SE for example Tropical Dry forest it sends an error like: `TypeError: np is undefined`
> 
> ![Screenshot_20220407_145352](https://user-images.githubusercontent.com/72577339/162285280-7c0d0df2-b9d6-4f17-9cf3-82bf0e607d99.png)
> 
> Take a look of this case: area_type=ea&area_id=CORPOCHIVOR

Fixed!

2022-04-08 16:10 UTC, cazapatamar commented on src/pages/Search.jsx
> +    const isMultipleLayers = rasterLayerIds.length > 1;
Fixed!

2022-04-08 16:17 UTC, erikasv commented on src/pages/Search.jsx
> +   * simultaneous layers in order to avoid return conection error if one fails
delete obsolete doc

2022-04-08 16:21 UTC, erikasv approved these changes

2022-04-08 16:24 UTC, merged