Migrate ForestIntegrity component
PEM-Humboldt/biotablero-frontend pull request #694
Opened 2022-08-03 19:42 UTC by erikasv

Some adjustments on other components were necessary

2022-08-04 10:03 UTC, Trjegul84 commented on src/pages/search/drawer/landscape/forest/ForestIntegrity.tsx
> +      .then((res: Array<SCIHF>) => {
In TimelinePAConnectivity this res was not highlighted for any type needed. In what cases this type definition for res will be needed?

2022-08-04 12:19 UTC, Trjegul84 commented on src/utils/searchAPI.ts
> +  ): Promise<Array<SCIHF>> {
Are the types needed also in requestTimelinePAConnectivity and also in all requests of restAPI.js ?

2022-08-04 12:31 UTC, erikasv commented on src/utils/searchAPI.ts
> +  ): Promise<Array<SCIHF>> {
Yes, we talk this last week, we're going to migrate requests from restAPI.js to SearchAPI.ts so we can type them progressively

2022-08-04 12:32 UTC, erikasv commented on src/pages/search/drawer/landscape/forest/ForestIntegrity.tsx
> +      .then((res: Array<SCIHF>) => {
Something must be wrong then, the type is required unless the other variables this response interacts with are any

2022-08-04 12:40 UTC, erikasv commented on src/pages/search/types/texts.ts
> +export interface TextObject {
I thought it was necessary only for set .js files types. I'll read about it

2022-08-04 21:03 UTC, cazapatamar approved these changes

2022-08-04 21:24 UTC, erikasv commented on src/pages/search/types/texts.ts
> +export interface TextObject {
According to the [documentation](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html) and [this answer](https://stackoverflow.com/a/50464124) I think `*.d.ts` files are appropriate to define common js modules (and they must have the same name as the module they are defining), so I wouldn't create the files with the shared types with this extension.

Last week we decided to create a file for each "*big accordion*" to hold shared definitions (that means types for the state will be in each component file and not in this folder `types`). I still like this decision, but if you have another suggestion we can discuss it.

Also @cazapatamar , @ManuelStardust what do you think?

2022-08-05 02:10 UTC, cazapatamar commented on src/pages/search/types/texts.ts
> +export interface TextObject {
Sorry i haven't read this comment.

I think having a ´*.d.ts´ file for every object retrieved from the dabatase could increase the complexity of the code and it would leads to have many independent files. I agree to create a file for each accordion and there hold all share definitions.

2022-08-05 14:05 UTC, Trjegul84 approved these changes

2022-08-05 17:02 UTC, cazapatamar requested changes

2022-08-05 17:02 UTC, cazapatamar commented on src/pages/search/drawer/landscape/forest/ForestIntegrity.tsx
> +      isDataNull,
This state is not used

2022-08-05 17:02 UTC, cazapatamar commented on src/utils/searchAPI.ts
>      areaId: string | number
It is necessary to put a comma at the end of this line?

2022-08-05 19:34 UTC, erikasv commented on src/pages/search/drawer/landscape/forest/ForestIntegrity.tsx
> +      isDataNull,
You're right, solved.

2022-08-05 19:35 UTC, erikasv commented on src/utils/searchAPI.ts
>      areaId: string | number
I thought so, but prettier remove is :woman_shrugging:

2022-08-05 20:06 UTC, cazapatamar approved these changes

2022-08-05 20:06 UTC, merged