Feature/type script timeline pa conn
PEM-Humboldt/biotablero-frontend pull request #696
Opened 2022-08-04 11:24 UTC by Trjegul84

2022-08-04 21:16 UTC, erikasv requested changes
Sorry, I left the messages this morning but forgot to send the review

2022-08-11 21:06 UTC, erikasv commented on src/pages/search/types/connectivity.ts
> +export const timelinePAConnKeys = ["prot", "prot_conn"] as const;
I think this should be just before `timeLinePAConnValues` to keep types some how related together, what do you all think?

2022-08-11 21:08 UTC, erikasv commented on src/pages/search/types/texts.types.d.ts
> +export interface InfoTexts {
I believe this file isn't being used? also I think is the same as `texts.ts` in the same folder, please delete it

2022-08-11 21:09 UTC, erikasv commented on src/pages/search/drawer/landscape/connectivity/TimelinePAConnectivity.tsx
> +import RestAPI from "utils/restAPI";
Remove unused import

2022-08-11 21:18 UTC, erikasv commented on src/pages/search/drawer/landscape/connectivity/TimelinePAConnectivity.tsx
> +              data: item.data.map((i: { x: string; y: number }) => ({
Replace `{ x: string; y: number }` for `timeLinePAConnValues` type (and export it from the other file)

2022-08-11 21:21 UTC, erikasv commented on src/pages/search/drawer/landscape/connectivity/TimelinePAConnectivity.tsx
> +        console.log(this.state);
Remove this line

2022-08-11 21:25 UTC, erikasv commented on src/pages/search/drawer/landscape/connectivity/TimelinePAConnectivity.tsx
> +              data: item.data.map((i: { x: string; y: number }) => ({
Replace `{ x: string; y: number }` for `timeLinePAConnValues` type (and export it from the other file)

2022-08-11 21:25 UTC, erikasv commented on src/pages/search/drawer/landscape/connectivity/TimelinePAConnectivity.tsx
> +        console.log(this.state);
Remove this line

2022-08-11 21:28 UTC, erikasv commented on src/pages/search/types/connectivity.ts
> +export const timelinePAConnKeys = ["prot", "prot_conn"] as const;
@cazapatamar @ManuelStardust

2022-08-12 02:33 UTC, Trjegul84 commented on src/pages/search/drawer/landscape/connectivity/TimelinePAConnectivity.tsx
> +import RestAPI from "utils/restAPI";
Done

2022-08-12 02:46 UTC, Trjegul84 commented on src/pages/search/types/texts.types.d.ts
> +export interface InfoTexts {
Done!

2022-08-12 02:47 UTC, Trjegul84 commented on src/pages/search/drawer/landscape/connectivity/TimelinePAConnectivity.tsx
> +              data: item.data.map((i: { x: string; y: number }) => ({
done!

2022-08-12 02:47 UTC, Trjegul84 commented on src/pages/search/drawer/landscape/connectivity/TimelinePAConnectivity.tsx
> +        console.log(this.state);
done!

2022-08-12 02:47 UTC, Trjegul84 commented on src/pages/search/drawer/landscape/connectivity/TimelinePAConnectivity.tsx
> +interface SearchContextValues {
done!

2022-08-12 02:48 UTC, Trjegul84 commented on src/pages/search/drawer/landscape/connectivity/TimelinePAConnectivity.tsx
> +import { InfoTexts } from "pages/search/types/texts.types";
ok

2022-08-12 14:09 UTC, Trjegul84 commented on src/pages/search/types/connectivity.ts
> +export const timelinePAConnKeys = ["prot", "prot_conn"] as const;
I think in the file is more organized the constant declarations grouped first and later the interfaces as you can find them easily but if the .ts file is large it could be better to place the constants just before the interfaces related.

2022-08-12 14:57 UTC, ManuelStardust commented on src/pages/search/types/connectivity.ts
> +export const timelinePAConnKeys = ["prot", "prot_conn"] as const;
I agree with @Trjegul84, in my opinion it is better to organize all the constants first and then the interfaces.

2022-08-12 15:05 UTC, erikasv commented on src/pages/search/types/connectivity.ts
> +export const timelinePAConnKeys = ["prot", "prot_conn"] as const;
Ok, lets keep it that way then.

2022-08-12 15:05 UTC, erikasv approved these changes

2022-08-12 15:06 UTC, merged