Migrate CurrentSEPAConnectivity to Typescript
PEM-Humboldt/biotablero-frontend pull request #717
Opened 2022-08-17 21:08 UTC by ManuelStardust

The component was converted to typescript, Prettier was executed on the component. The correct functioning of the component was verified.

2022-08-17 22:12 UTC, erikasv requested changes

2022-08-17 22:12 UTC, erikasv commented on src/pages/search/drawer/landscape/connectivity/CurrentSEPAConnectivity.tsx
> +interface Props {}
We've been using `any` for components without props, I think the empty object is better, but I think it would be necessary to change all already migrated components without props, so they also have an empty object as props.

So... would you mind to do that? (also I already merged the ForestLoss PR, so you would need to merge `feature/typescriptPOC` into your branch)

2022-08-17 22:12 UTC, erikasv commented on src/utils/searchAPI.ts
> +   *
You're missing the documentation of a parameter, and the description is missing the strategic ecosystem part. See `requestCurrentPAConnectivityBySE` in *restAPI.js*, also delete the old function in that file, unless is being used from another file (I don't think so)

2022-08-17 22:18 UTC, erikasv commented
Also please delete the other branches (the ones from the closed PRs)

2022-08-18 13:50 UTC, Trjegul84 commented on src/pages/search/drawer/landscape/connectivity/CurrentSEPAConnectivity.tsx
> +interface Props {}
Also in TimelinePAConnectivity component we have any in the props. Should we change in other task or in this one ?

2022-08-18 18:17 UTC, ManuelStardust commented on src/utils/searchAPI.ts
> +   *
Solved. Thanks for the review.

2022-08-18 18:21 UTC, ManuelStardust commented on src/pages/search/drawer/landscape/connectivity/CurrentSEPAConnectivity.tsx
> +interface Props {}
Props definition updated in all components previously migrated to Typescript. @Trjegul84 Don't worry this component was also updated in this task.

2022-08-18 18:34 UTC, Trjegul84 commented on src/pages/search/drawer/landscape/connectivity/CurrentSEPAConnectivity.tsx
> +interface Props {}
Thanks.

2022-08-18 19:00 UTC, erikasv requested changes

2022-08-18 21:20 UTC, ManuelStardust commented on src/pages/search/drawer/landscape/connectivity/TimelinePAConnectivity.tsx
> +interface Props {}
Fixed

2022-08-18 21:20 UTC, ManuelStardust commented on src/utils/restAPI.js
> +import axios, { CancelToken } from "axios";
Fixed too.

2022-08-18 21:23 UTC, erikasv approved these changes

2022-08-19 13:11 UTC, cazapatamar approved these changes
Ready to be merged. @ManuelStardust please merge this branch as soon as you can in order to avoid heavy conflicts once we merge our branches.

2022-08-19 13:32 UTC, merged