Migrate to typescript compensation factor component
PEM-Humboldt/biotablero-frontend pull request #719
Opened 2022-08-18 18:14 UTC by cazapatamar

2022-08-18 20:57 UTC, erikasv requested changes

2022-08-18 20:57 UTC, erikasv commented on src/pages/search/drawer/landscape/CompensationFactor.tsx
>              texts: { ...prevState.texts, [item]: {} },
I think is because of the `[item]` this line doesn't throw the ts error thrown in other components, but as for the type definition it's better to just not do anything in case of failure (in no other place are the texts modified, so the structure would be kept)

2022-08-18 20:57 UTC, erikasv commented on src/pages/search/drawer/landscape/CompensationFactor.tsx
> +    const { areaId, geofenceId, handlerClickOnGraph } = this
Why did you added `handlerClickOnGraph` ? it's not used

2022-08-19 00:30 UTC, cazapatamar commented on src/pages/search/drawer/landscape/CompensationFactor.tsx
>              texts: { ...prevState.texts, [item]: {} },
Do you mean ..... `[item]: { info: "", cons: "", meto: "", quote: "" }`?

2022-08-19 00:33 UTC, cazapatamar commented on src/pages/search/drawer/landscape/CompensationFactor.tsx
> +    const { areaId, geofenceId, handlerClickOnGraph } = this
Fixed!

2022-08-19 11:54 UTC, erikasv commented on src/pages/search/drawer/landscape/CompensationFactor.tsx
>              texts: { ...prevState.texts, [item]: {} },
Yeap, see in other components that the catch for the test simply doesn't do anything

2022-08-19 12:32 UTC, cazapatamar commented on src/pages/search/drawer/landscape/CompensationFactor.tsx
>              texts: { ...prevState.texts, [item]: {} },
Ok i will fix it.

2022-08-19 13:29 UTC, erikasv approved these changes
Pleas wait until the PR [717](https://github.com/PEM-Humboldt/biotablero-frontend/pull/717) is merged

2022-08-19 15:09 UTC, merged