Migrate strategic ecosystems to typescript
PEM-Humboldt/biotablero-frontend pull request #721
Opened 2022-08-18 22:55 UTC by Trjegul84

Please help me with this questions:

1. In `SearchAPI` I place the ecosystems section below the human footprint section, is there any order established for adding the sections there?

1. Also the `PAData` interface defined has the label as string because it has a lot of options. Should all the options for the label property be defined in a constant in ecosystems.ts  ?

1.  In this task, Should I migrate to typescript the `Ecosystems.jsx `component also?  

1. The endpoint related with `requestSEPAByGeofence` returns something like  
```
[
  {
    "area": 447657.310088262,
    "type": "Parque Nacional Natural"
  }
]
```
  But I set the response as an array of `PAData` as far I can understand the return of `transformPAValues` function and you can see the structure of that object is different. Should I need different typescript interface for this response only with `area` and `type` or it is ok setting the return as  `Promise<Array<PAData>>`

2022-08-19 13:14 UTC, erikasv requested changes

2022-08-19 13:14 UTC, erikasv commented on src/pages/search/types/ecosystems.ts
> +export interface CoverageData {
Also, once you move the specific component use definitions to that file, the coverageLabels should be moved to the component too

2022-08-19 13:14 UTC, erikasv commented on src/pages/search/types/ecosystems.ts
> +export interface PAData {
According to the documentation, the endpoint returns an array of objects with 'area' and 'type'. Please check that the documentation is up to date and make the same fix o the two previous interfaces

2022-08-19 13:24 UTC, erikasv commented
>     1. In `SearchAPI` I place the ecosystems section below the human footprint section, is there any order established for adding the sections there?
There is no order, just grouping, it's ok there

>     2. Also the `PAData` interface defined has the label as string because it has a lot of options. Should all the options for the label property be defined in a constant in ecosystems.ts  ?
I didn't notice those mentioned options, maybe explain them in the daily

>     3. In this task, Should I migrate to typescript the `Ecosystems.jsx `component also?
No, actually I was thinking only in one of the two components you migrated xD

>     4. The endpoint related with `requestSEPAByGeofence` returns something like
> ...
> But I set the response as an array of `PAData` as far I can understand the return of `transformPAValues` function and you can see the structure of that object is different. Should I need different typescript interface for this response only with `area` and `type` or it is ok setting the return as `Promise<Array<PAData>>`
Seethr comments in the code

2022-08-19 22:59 UTC, Trjegul84 commented on src/pages/search/drawer/strategicEcosystems/EcosystemsBox.tsx
> +  setActiveSE: (type: string) => {};
done!

2022-08-19 22:59 UTC, Trjegul84 commented on src/pages/search/drawer/strategicEcosystems/EcosystemsBox.tsx
> +import SearchContext from "pages/search/SearchContext";
removed!

2022-08-22 15:53 UTC, erikasv requested changes

2022-08-22 15:53 UTC, erikasv commented on src/utils/searchAPI.ts
> +
These functions should be under the ecosystems section, not in the middle of footprint

2022-08-22 15:53 UTC, erikasv commented on src/utils/restAPI.js
> +import axios, { CancelToken } from "axios";
Undo the format changes in this file so we can see the relevant changes

2022-08-22 16:39 UTC, Trjegul84 commented on src/utils/restAPI.js
> +import axios, { CancelToken } from "axios";
done!

2022-08-22 16:59 UTC, erikasv approved these changes

2022-08-22 17:00 UTC, merged