Replace Graph Loader with withMessageWrapper HOC
PEM-Humboldt/biotablero-frontend pull request #731
Opened 2022-08-25 22:36 UTC by erikasv

Created withMessageWrapper HOC to wrap all charts and use the chart directly from the components.

Some changes had to be made on the types of props and states of some components

2022-08-26 19:38 UTC, cazapatamar requested changes

2022-08-26 19:38 UTC, cazapatamar commented on src/pages/search/drawer/landscape/connectivity/CurrentPAConnectivity.tsx
> +            <MultiSmallSingleBarGraph
There is a problem with height of this graph

![imagen](https://user-images.githubusercontent.com/19979979/186978534-d9f2c4b1-37a6-4e91-aca7-4632ce64864d.png)

2022-08-26 19:38 UTC, cazapatamar commented on src/pages/search/drawer/landscape/connectivity/TimelinePAConnectivity.tsx
>                graphType="MultiLinesGraph"
I think we should delete this prop as it is not used anymore.

Also, there is a warning related to onClickGraphHandler marked as required

![imagen](https://user-images.githubusercontent.com/19979979/186978913-6626aff9-4e4b-473d-8c03-d2ba685fad1b.png)

2022-08-26 19:40 UTC, cazapatamar commented
Clic is not working on SingleBulletGraph (Number of especies and Functional Diversity)

![imagen](https://user-images.githubusercontent.com/19979979/186979345-c8dbe3a1-5fec-4bf4-940e-6142e58f9926.png)

![imagen](https://user-images.githubusercontent.com/19979979/186979417-a1711482-2daa-4430-ab18-93566577b704.png)

2022-08-26 19:53 UTC, erikasv commented on src/pages/search/drawer/landscape/connectivity/CurrentPAConnectivity.tsx
> +            <MultiSmallSingleBarGraph
the worst part is that I already have seen that... don't know what happened with that change xD

2022-08-26 19:55 UTC, erikasv commented on src/pages/search/drawer/landscape/connectivity/TimelinePAConnectivity.tsx
>                graphType="MultiLinesGraph"
fixed

2022-08-26 19:59 UTC, cazapatamar commented on src/pages/search/drawer/landscape/connectivity/CurrentPAConnectivity.tsx
> +            <MultiSmallSingleBarGraph
That's normal in a huge refactor like this :D

2022-08-26 20:01 UTC, erikasv commented
> Clic is not working on SingleBulletGraph (Number of especies and Functional Diversity)

Fixed... This wouldn't have happened with ts xD

2022-08-29 13:22 UTC, Trjegul84 approved these changes

2022-08-29 13:30 UTC, merged