Migrate Tabcontainer and Accordion components to Typescript
PEM-Humboldt/biotablero-frontend pull request #760
Opened 2022-09-21 12:56 UTC by ManuelStardust

- Migrate Accordion component. 
- Update Landscape, Forest HumanFootprint and PAConnectivity
- Migrate Tabcontainer component

2022-09-21 20:24 UTC, erikasv requested changes

2022-09-21 20:24 UTC, erikasv commented on src/pages/search/shared_components/TabContainer.tsx
> +  icon?: string | ReactElement;
what is the purpose of this prop being optional and allowing strings? I see the only place where this component is used it always send the icon and is an element.

2022-09-21 20:24 UTC, erikasv commented on src/pages/search/shared_components/TabContainer.tsx
> +  selected?: string;
This prop isn't being used

2022-09-21 20:24 UTC, erikasv commented on src/pages/search/shared_components/TabContainer.tsx
> +      initialSelectedIndex = 1,
this prop isn't being used here

2022-09-21 20:24 UTC, erikasv commented on src/pages/search/shared_components/TabContainer.tsx
> +  value: number;
Change this state name to `selectedIndex` or something like that, `value`is a terrible name (I know it was like that before :woman_facepalming: )

2022-09-21 21:04 UTC, erikasv commented
Also please connect the corresponding issue

2022-09-22 12:54 UTC, ManuelStardust commented on src/pages/search/shared_components/TabContainer.tsx
> +  icon?: string | ReactElement;
You're right. solved.

2022-09-22 12:55 UTC, ManuelStardust commented on src/pages/search/shared_components/TabContainer.tsx
> +  selected?: string;
Solved

2022-09-22 12:55 UTC, ManuelStardust commented on src/pages/search/shared_components/TabContainer.tsx
> +      initialSelectedIndex = 1,
Solved

2022-09-22 12:57 UTC, ManuelStardust commented on src/pages/search/shared_components/TabContainer.tsx
> +  value: number;
Done. I will keep it in mind for the future.

2022-09-22 14:26 UTC, erikasv approved these changes

2022-09-22 14:38 UTC, merged