Portfolios section 1: Portfolios by target
PEM-Humboldt/biotablero-frontend pull request #763
Opened 2022-09-29 22:27 UTC by ManuelStardust

- Create a new tab for portfolios view
- Create conservation area portfolios api function
- Create conservation area portfolios component
- Create portfolios by target component

2022-09-29 23:40 UTC, erikasv commented
You're missing the textboxes and the download button

2022-09-30 00:14 UTC, ManuelStardust commented
Sorry, I put an emty component to this features. I'm going to set dummy values for texts to get the preview.

2022-09-30 02:33 UTC, erikasv requested changes
To better check the correct functionality of the accordions, add a new tab in each one, that way you can check the behavior is the expected one and then remove the extra tab.

2022-09-30 02:33 UTC, erikasv commented on src/pages/search/drawer/Portfolios.tsx
> +  childMap: {};
this object must contain a map between bigger accordion (key) and inner accordion open (value)

2022-09-30 02:33 UTC, erikasv commented on src/pages/search/drawer/Portfolios.tsx
> +    const { childMap } = this.state;
These variables aren't used

2022-09-30 02:33 UTC, erikasv commented on src/pages/search/drawer/portfolios/ConservationAreas.tsx
> +  const { handleAccordionChange, openTab } = props;
both props will be undefined always, since you are not sending them from Portfolios

2022-09-30 02:33 UTC, erikasv commented on src/pages/search/drawer/portfolios/ConservationAreas.tsx
> +  const { handleAccordionChange, openTab } = props;
Also you are not using openTab

2022-09-30 02:33 UTC, erikasv commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +
why the separation among these imports?

2022-09-30 02:33 UTC, erikasv commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +  messageConc?: string | null;
what does `messageConc` stands for?

2022-09-30 02:33 UTC, erikasv commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +      loading: null,
`loading` never changes value

2022-09-30 02:33 UTC, erikasv commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +      showErrorMessage: false,
this state is never used

2022-09-30 02:33 UTC, erikasv commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +  targetsList?: Array<target>;
targetList shouldn't be optional

2022-09-30 02:33 UTC, erikasv commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +      selected: "",
this state is never used

2022-09-30 02:33 UTC, erikasv commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +  getPortfolioData = (targetId: number) => {
this function is never called

2022-09-30 02:33 UTC, erikasv commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +        this.setState({ messageConc: "no-data" });
You're assigning `messageConc` values used in other components as wrapperMessage, nevertheless, only `loading` is of that type

2022-09-30 02:33 UTC, erikasv commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +  targetData?: portfoliosByTarget;
targetData shouldn't be optional

2022-09-30 02:33 UTC, erikasv commented on src/utils/searchAPI.ts
> +  static TargetsList(
better keep the standard `request<Something>`

2022-09-30 02:33 UTC, erikasv commented on src/utils/searchAPI.ts
> +  static PortfoliosByTarget(
better keep the standard `requestPortfoliosByTarget`

2022-09-30 02:33 UTC, erikasv commented on src/pages/search/types/portfolios.ts
> +export interface portfolioData {
this interface doesn't need to be exported, it can even be declared inside `portfoliosByTarget`

2022-09-30 02:33 UTC, erikasv commented on src/utils/searchAPI.ts
> +   * @param {String} targetId target id to get results
number

2022-09-30 02:33 UTC, erikasv commented on src/utils/searchAPI.ts
> +   * @return {Promise<Object>} Array of objects with targets list
returns an array of objects

2022-09-30 22:10 UTC, ManuelStardust commented on src/utils/searchAPI.ts
> +   * @return {Promise<Object>} Array of objects with targets list
Fixed

2022-09-30 22:11 UTC, ManuelStardust commented on src/pages/search/types/portfolios.ts
> +export interface portfolioData {
Fixed

2022-09-30 22:11 UTC, ManuelStardust commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +
Fixed

2022-09-30 22:12 UTC, ManuelStardust commented on src/pages/search/drawer/Portfolios.tsx
> +  childMap: {};
Fixed

2022-09-30 22:13 UTC, ManuelStardust commented on src/pages/search/drawer/Portfolios.tsx
> +    }));
Fixed

2022-09-30 22:14 UTC, ManuelStardust commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +  messageConc?: string | null;
It was a mistake, loading is the selected var for loading text

2022-09-30 22:15 UTC, ManuelStardust commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +      showErrorMessage: false,
Removed

2022-09-30 22:15 UTC, ManuelStardust commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +      selected: "",
Removed

2022-09-30 22:15 UTC, ManuelStardust commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +  targetsList?: Array<target>;
Fixed

2022-09-30 22:16 UTC, ManuelStardust commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +  getPortfolioData = (targetId: number) => {
Fixed, now is calling from componentDidMount when get the list of targets

2022-09-30 22:17 UTC, ManuelStardust commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +        this.setState({ messageConc: "no-data" });
Fixed

2022-09-30 22:17 UTC, ManuelStardust commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +  targetData?: portfoliosByTarget;
Fixed

2022-09-30 22:17 UTC, ManuelStardust commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +      loading: null,
Fixed

2022-10-01 01:27 UTC, erikasv approved these changes

2022-10-01 01:29 UTC, merged