Migrate draw polygon related components to ts
PEM-Humboldt/biotablero-frontend pull request #764
Opened 2022-09-30 21:51 UTC by erikasv

2022-09-30 23:59 UTC, ManuelStardust requested changes

2022-09-30 23:59 UTC, ManuelStardust commented on src/pages/search/selector/PolygonIcon.tsx
> +import PropTypes from "prop-types";
this import is never used

2022-09-30 23:59 UTC, ManuelStardust commented on src/pages/search/selector/PolygonIcon.tsx
> +import React from "react";
this import is never used

2022-09-30 23:59 UTC, ManuelStardust commented on src/pages/search/selector/DrawPolygon.tsx
>            componentsArray={instructions}
instructions must be of type array accordionComponent

2022-09-30 23:59 UTC, ManuelStardust commented on src/pages/search/selector/EditIcon.tsx
> +import PropTypes from "prop-types";
this import is never used

2022-09-30 23:59 UTC, ManuelStardust commented on src/pages/search/selector/EditIcon.tsx
> +import React from "react";
this import is never used

2022-09-30 23:59 UTC, ManuelStardust commented on src/pages/search/selector/RemoveIcon.tsx
> +import PropTypes from "prop-types";
this import is never used

2022-09-30 23:59 UTC, ManuelStardust commented on src/pages/search/selector/RemoveIcon.tsx
> +import React from "react";
this import is never used

2022-10-01 00:07 UTC, erikasv commented on src/pages/search/selector/DrawPolygon.tsx
>            componentsArray={instructions}
What do you mean? its objects have the required properties defined by accordionComponent

2022-10-01 00:17 UTC, ManuelStardust commented on src/pages/search/selector/DrawPolygon.tsx
>            componentsArray={instructions}
Yes, you are right, visual studio was showing me that error but not anymore

2022-10-01 00:23 UTC, erikasv commented on src/pages/search/selector/DrawPolygon.tsx
>            componentsArray={instructions}
Ah ok, for the record I did change the expected type for the label name, and it can be useful to restart the typescript server in code when you change branches (ctrl + shit + p -> TypeScript: restart TS server )

2022-10-01 01:27 UTC, ManuelStardust approved these changes

2022-10-01 01:28 UTC, merged