Feature/portfolios ca layers
PEM-Humboldt/biotablero-frontend pull request #781
Opened 2022-10-28 15:42 UTC by ManuelStardust

- Add portfolios CA layers request for the first target

2022-10-28 20:57 UTC, cazapatamar requested changes

2022-10-28 20:57 UTC, cazapatamar commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +                      );
Please add a condition when there is not portfolios ids (portfoliosIds is empty) in order to avoid call switchLayer in this case

2022-10-28 20:57 UTC, cazapatamar commented on src/utils/searchAPI.ts
> +  ) {
Add retrurn type for requestPortfoliosCALayer

2022-10-28 20:57 UTC, cazapatamar commented on src/pages/Search.jsx
> +            rasterLayerOpts.push({ id: `portfoliosCA-${portfolioId}` });
Add paneLevel attribute

2022-10-28 22:41 UTC, ManuelStardust commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +                      );
Done

2022-10-28 22:41 UTC, ManuelStardust commented on src/utils/searchAPI.ts
> +  ) {
Done

2022-10-28 22:41 UTC, ManuelStardust commented on src/pages/Search.jsx
> +            rasterLayerOpts.push({ id: `portfoliosCA-${portfolioId}` });
Done

2022-10-28 22:52 UTC, cazapatamar approved these changes

2022-10-28 22:58 UTC, merged

2022-10-31 01:22 UTC, erikasv commented on src/utils/searchAPI.ts
> +  static requestPortfoliosCALayer(
You need to return the cancelToken, otherwise the whole function in Search might fail

2022-10-31 01:23 UTC, erikasv commented on src/pages/Search.jsx
> +export default withRouter(Search);
The file must end with a newline

2022-10-31 01:24 UTC, erikasv commented on src/pages/Search.jsx
> +      const [, portfolioId] = layerName.match(/portfoliosCA-(\w+)/);
this regex pattern should be the same as the one in setSectionLayers