Post Polygon Submit View
PEM-Humboldt/biotablero-frontend pull request #792
Opened 2022-11-15 14:28 UTC by ManuelStardust

2022-11-15 20:59 UTC, erikasv requested changes

2022-11-15 20:59 UTC, erikasv commented on src/pages/Search.jsx
> +  setSearchType(searchType) {
change this to arrow function

2022-11-15 20:59 UTC, erikasv commented on src/pages/Search.jsx
> +              setSearchType={this.setSearchType.bind(this)}
remove the `bind` part (with arrow function it's not necessary)

2022-11-15 20:59 UTC, erikasv commented on src/pages/search/mapViewer/DrawControl.jsx
> +DrawControl.contextType = SearchContext;
add newline at the end

2022-11-15 20:59 UTC, erikasv commented on src/pages/Search.jsx
> +              setSearchType={this.setSearchType.bind(this)}
Also these 2 props aren't necessary, both calls can be done inside `loadPolygonInfo` in this same component

2022-11-15 20:59 UTC, erikasv commented on src/pages/search/drawer/Ecosystems.jsx
> +    if(searchType!=="polygon"){
Change the condition to return if it's "polygon" and avoid the extra indentation level

2022-11-15 20:59 UTC, erikasv commented on src/pages/search/drawer/Ecosystems.jsx
> +    if(searchType!=="polygon"){
Also, since we had to deactivate eslint, pay more attention to code style, in this case add a space after the `if` and between the comparation symbol

2022-11-15 20:59 UTC, erikasv commented on src/pages/search/drawer/Ecosystems.jsx
> +    }else{
this else is unnecessary, remove it and avoid the extra indentation

2022-11-15 20:59 UTC, erikasv commented on src/pages/search/drawer/Ecosystems.jsx
> +    if(searchType==="polygon"){
please fix style (see comment above)

2022-11-15 20:59 UTC, erikasv commented on src/pages/search/drawer/Species.jsx
> +    if(searchType!=="selected"){
"selected" isn't a valid value for this variable, this is working only because `areaId` is null and it's entering the default case

2022-11-15 20:59 UTC, erikasv commented on src/pages/search/drawer/Species.jsx
> +    if(searchType!=="selected"){
Also I don't see the if necessary, @cazapatamar I think we could handle this inside the default case of the switch, later if it's necessary something for the polygon we can change it. What do you think?

Also this would apply for all Tabs (Landscape and Portfolios), and just make sure when setting `searchType` to polygon to also set areaId and geofenceId to null

2022-11-15 20:59 UTC, erikasv commented on src/pages/search/drawer/landscape/Forest.tsx
> +  const { searchType } = useContext(SearchContext);
In the Search module we don't use hooks, It's ok for me to have a combination of classes and hooks (we have hooks in other modules already), but I don't know if it can be confusing, @cazapatamar how would you feel about it?

2022-11-15 20:59 UTC, erikasv commented on src/pages/search/drawer/landscape/forest/ForestLossPersistence.tsx
> +        .getForestLPData(areaId, geofenceId, LATEST_PERIOD)
hardcode an area, don't leave `areaId` and `geofenceId` since they are null

2022-11-15 20:59 UTC, erikasv commented on src/pages/search/drawer/landscape/forest/ForestLossPersistence.tsx
> +        .getForestLPData(areaId, geofenceId, LATEST_PERIOD)
Also, I think this logic should go inside the controller, I don't like this giant if. `getForestLPData` should receive everything and return the data the way it can be stored in the state.

For example, it could receive `areaId`, `geofenceId`, `searchType` and the polygon.

2022-11-15 20:59 UTC, erikasv commented on src/pages/search/SearchContext.tsx
> +  searchType: "selection" | "polygon";
I think you need to store the polygon in the context too, or it would be necessary to pass it down as prop or to manage all requests from Search, which is a bad idea

2022-11-15 23:45 UTC, cazapatamar commented on src/pages/search/drawer/Species.jsx
> +    if(searchType!=="selected"){
Yes, i think we can delete that unuseful condition and use de default case to handle when there is a selected geofence or a polygon. Likely in the near future we can use a similar `if` when we are clearer about what to do in each case.

2022-11-16 00:18 UTC, cazapatamar commented on src/pages/search/SearchContext.tsx
> +  searchType: "selection" | "polygon";
@erikasv are you ok with `selection` name for this option? I think it sounds too general and i like better something like `geofence`, `defGeofence`, `definedGeofence` or similar. Anyway if you agree with `selection` it is ok for me.

On the other hand, i don't like `polygon` either considering in the future (long future) we can implement the option to upload a polygon and specific rules associated, so this name in the context could be too general. I suggest a name like `drawPolygon` or similar.

2022-11-16 01:19 UTC, erikasv commented on src/pages/search/drawer/landscape/Forest.tsx
> +  const { searchType } = useContext(SearchContext);
I see, We can discuss it tomorrow, but I think that if we want to use hooks in the module, starting with the big accordion components (like this case: `Forest`) would be a good point

2022-11-16 01:21 UTC, erikasv commented on src/pages/search/SearchContext.tsx
> +  searchType: "selection" | "polygon";
Yes, I agree with your suggestions, I like more `definedArea` (more than "geofence" since we started deprecating the word a while ago xD) and `drawPolygon`

2022-11-16 01:24 UTC, cazapatamar commented on src/pages/search/SearchContext.tsx
> +  searchType: "selection" | "polygon";
definedArea sounds good

2022-11-17 20:33 UTC, ManuelStardust commented on src/pages/search/SearchContext.tsx
> +  searchType: "selection" | "polygon";
Done

2022-11-17 20:35 UTC, ManuelStardust commented on src/pages/search/SearchContext.tsx
> +  searchType: "selection" | "polygon";
Done, I added a context var called polygonRequest

2022-11-17 20:36 UTC, ManuelStardust commented on src/pages/search/drawer/landscape/forest/ForestLossPersistence.tsx
> +        .getForestLPData(areaId, geofenceId, LATEST_PERIOD)
Done

2022-11-17 20:36 UTC, ManuelStardust commented on src/pages/search/drawer/Species.jsx
> +    if(searchType!=="selected"){
Done

2022-11-17 20:38 UTC, ManuelStardust commented on src/pages/Search.jsx
> +  setSearchType(searchType) {
This function was removed, the change in searchType is done directly in _loadPolygonInfo_

2022-11-17 20:38 UTC, ManuelStardust commented on src/pages/Search.jsx
> +              setSearchType={this.setSearchType.bind(this)}
Done.

2022-11-17 20:39 UTC, ManuelStardust commented on src/pages/search/mapViewer/DrawControl.jsx
> +DrawControl.contextType = SearchContext;
Done

2022-11-17 20:39 UTC, ManuelStardust commented on src/pages/search/drawer/Ecosystems.jsx
> +    if(searchType!=="polygon"){
Done

2022-11-17 20:40 UTC, ManuelStardust commented on src/pages/search/drawer/Ecosystems.jsx
> +    }else{
Done

2022-11-17 20:40 UTC, ManuelStardust commented on src/pages/search/drawer/Ecosystems.jsx
> +    if(searchType==="polygon"){
Done

2022-11-17 21:10 UTC, erikasv commented on src/pages/search/SearchContext.tsx
> +  polygonRequest: {} as Polygon,
what is the purpose of `as Polygon` ?

2022-11-17 21:12 UTC, erikasv commented on src/pages/search/SearchContext.tsx
> +  polygonRequest: {};
`polygonRequest` is always an empty object?

2022-11-17 21:15 UTC, erikasv commented on src/pages/search/drawer/landscape/forest/ForestLossPersistenceController.ts
> +    polygonRequest: {}
Why would this always be an empty object?

2022-11-17 22:06 UTC, ManuelStardust commented on src/pages/search/SearchContext.tsx
> +  polygonRequest: {} as Polygon,
It's because initially when I declared the empty object it generated an error, and the way I found to solve it was this. However, checking again I think that I can initialize the variable in the following way: _polygonRequest: { latLngs: [] }_, what do you think?

2022-11-18 15:07 UTC, ManuelStardust commented on src/pages/search/SearchContext.tsx
> +  polygonRequest: {} as Polygon,
Fixed

2022-11-18 15:07 UTC, ManuelStardust commented on src/pages/search/SearchContext.tsx
> +  polygonRequest: {};
Fixed

2022-11-18 15:52 UTC, erikasv commented on src/pages/Search.jsx
> +      selectedAreaId: "",
It's better accept null for these 2 variables in the context, I see in the constructor and in `handlerBackButton` they are being set to null

2022-11-18 15:53 UTC, erikasv commented on src/pages/search/drawer/landscape/forest/ForestLossPersistenceController.ts
> +   * @param {String} searchType string to identifyy the type of search
typo in identifyy

2022-11-18 15:54 UTC, erikasv commented on src/pages/search/drawer/landscape/forest/ForestLossPersistenceController.ts
> +   * @param {Object | null} polygonRequest object with range of years for latest period
I don't understand this description what do you mean with `with range of years for latest period`?

2022-11-18 17:01 UTC, ManuelStardust commented on src/pages/search/drawer/landscape/forest/ForestLossPersistenceController.ts
> +   * @param {Object | null} polygonRequest object with range of years for latest period
Sorry, it was my mistake. Fixed.

2022-11-18 19:48 UTC, ManuelStardust commented on src/pages/Search.jsx
> +      selectedAreaId: "",
Done

2022-11-18 20:58 UTC, erikasv approved these changes

2022-11-18 20:59 UTC, merged