Set behavior of the information buttons for portfolios and targets
PEM-Humboldt/biotablero-frontend pull request #796
Opened 2022-11-22 17:59 UTC by ManuelStardust

2022-11-22 20:50 UTC, erikasv requested changes

2022-11-22 20:50 UTC, erikasv commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +   * Set information texts for each target
This function actually updates the current shown texts

2022-11-22 20:50 UTC, erikasv commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +  setGraphTexts = (targetName: string) => {
I don't see `targetsTexts` being used for anything related with the ui, this and the function to return the correct group of text should be in the controller

2022-11-22 20:50 UTC, erikasv commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +    );
This selection is very confusing, it would be easier to understand if instead of an array of objects `targetsTexts` is just an object, or if every object has a prop `name` or `id` to filter by it

2022-11-22 20:50 UTC, erikasv commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +    );
Same comments as the previous function

2022-11-22 20:50 UTC, erikasv commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +  };
I found a little confusing the use of 2 variables for this, but the implementation is ok. Would it be more confusing use just one variable? like this:
```js
    if (portfolioName === shownPortfolio) {
      this.setState({ shownPortfolio: null });
    } else {
      this.setState({ shownPortfolio: portfolioName });
    }
```
And the render section would still be as it is right now.

What do you think @cazapatamar @ManuelStardust ?

2022-11-22 20:50 UTC, erikasv commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +
This shouldn't be necessary, the texts should be initialized with the target selected in componentDidMount, if it's not selected there it's because there are no data

2022-11-22 20:51 UTC, erikasv commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +  setGraphTexts = (targetName: string) => {
see `getPortfoliosIdsByTarget` in te controller as an example

2022-11-22 23:52 UTC, ManuelStardust commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +  };
You're right, I agree. This part is easier this way.

2022-11-23 14:04 UTC, cazapatamar commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +  };
@erikasv I think using just one state is clear and redeable. Algo agree!

2022-11-23 14:40 UTC, ManuelStardust commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +    );
Solved

2022-11-23 14:40 UTC, ManuelStardust commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +    );
Solved

2022-11-23 14:40 UTC, ManuelStardust commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +
Solved

2022-11-23 19:41 UTC, erikasv requested changes

2022-11-23 19:41 UTC, erikasv commented on src/pages/search/drawer/portfolios/conservationAreas/TargetsController.ts
> +  getTargetsInfoText(targetName: string) {
`getTargetsInfoTexts` and `getTargetsInfoText` are too similar, if you change the first one, it's ok to let this one like that

2022-11-23 19:41 UTC, erikasv commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +      shownPortfolio: "",
Shouldn't be `null` the initial state?

2022-11-23 19:41 UTC, erikasv commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +  portfoliosDescription: string;
should be singular

2022-11-24 12:36 UTC, ManuelStardust commented on src/pages/search/drawer/portfolios/conservationAreas/TargetsController.ts
> +  getPortfoliosTexts() {
Solved

2022-11-24 12:37 UTC, ManuelStardust commented on src/pages/search/drawer/portfolios/conservationAreas/TargetsController.ts
> +  getTargetsInfoTexts() {
Solved

2022-11-24 12:38 UTC, ManuelStardust commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +    this.targetsController.getTargetsInfoTexts();
Done

2022-11-24 12:38 UTC, ManuelStardust commented on src/pages/search/drawer/portfolios/conservationAreas/TargetsController.ts
> +  getTargetsInfoText(targetName: string) {
Done

2022-11-24 12:38 UTC, ManuelStardust commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +      shownPortfolio: "",
Done

2022-11-24 12:38 UTC, ManuelStardust commented on src/pages/search/drawer/portfolios/conservationAreas/Targets.tsx
> +  portfoliosDescription: string;
Done

2022-11-24 15:41 UTC, erikasv approved these changes

2022-11-24 15:51 UTC, merged