Message for selector when there is no connection or loading
PEM-Humboldt/biotablero-frontend pull request #824
Opened 2023-03-31 22:38 UTC by cazapatamar

2023-04-04 16:02 UTC, erikasv requested changes

2023-04-04 16:02 UTC, erikasv commented on src/pages/Search.jsx
> +          open={messages.defAreas === 'conn-error' && messages.polygon === 'conn-error' && openErrorModal}
the first two conditions are redundant, just with the `openErrorModal` is enough

2023-04-10 15:21 UTC, cazapatamar commented on src/pages/Search.jsx
> +          open={messages.defAreas === 'conn-error' && messages.polygon === 'conn-error' && openErrorModal}
Done!

2023-04-10 15:26 UTC, erikasv approved these changes

2023-04-10 15:30 UTC, merged