Polygon switch layer
PEM-Humboldt/biotablero-frontend pull request #835
Opened 2023-06-02 16:28 UTC by cazapatamar

2023-06-02 18:17 UTC, ManuelStardust requested changes

2023-06-02 18:17 UTC, ManuelStardust commented on src/pages/Search.jsx
> +      /* newState.polygonArea = 0; */
This line is commented but it is no longer useful

2023-06-02 20:34 UTC, cazapatamar commented on src/pages/Search.jsx
> +      /* newState.polygonArea = 0; */
Fixed!

2023-06-02 20:55 UTC, erikasv commented on src/pages/search/SearchContext.tsx
> +  switchLayer(layer: string | undefined | null): void;
these options are not necessary

2023-06-02 21:49 UTC, ManuelStardust approved these changes

2023-06-02 21:50 UTC, erikasv requested changes
Sorry I forgot to ask the changes in the comment I left before.

2023-06-05 13:57 UTC, cazapatamar commented on src/pages/search/SearchContext.tsx
> +  switchLayer(layer: string | undefined | null): void;
As `switchLayer` has these cases (`undefined` and `null`) i change here the options that function could receive.

2023-06-05 15:17 UTC, cazapatamar commented on src/pages/search/SearchContext.tsx
> +  switchLayer(layer: string | undefined | null): void;
Fixed!

2023-06-05 19:36 UTC, erikasv approved these changes

2023-06-05 19:42 UTC, merged