Update polygon request
PEM-Humboldt/biotablero-frontend pull request #849
Opened 2023-07-27 12:16 UTC by ManuelStardust

Update the request for the query of loss and persistence by polygon according to the current script.

2023-07-28 21:41 UTC, cazapatamar requested changes

2023-07-28 21:41 UTC, cazapatamar commented on src/pages/search/drawer/landscape/forest/ForestLossPersistenceController.ts
> +          const layersFolder = data.files.dir_png;
Consider handle the case when `data.files` is null or undefined

2023-07-28 22:32 UTC, ManuelStardust commented on src/pages/search/drawer/landscape/forest/ForestLossPersistenceController.ts
> +          const layersFolder = data.files.dir_png;
Done

2023-07-28 22:48 UTC, cazapatamar requested changes

2023-07-28 22:48 UTC, cazapatamar commented on src/pages/search/drawer/landscape/forest/ForestLossPersistenceController.ts
> +          const layersFolder = data.files.dir_png ?? "";
This solution handle the case when `dir_png` is null or undefined but not when `files` is null or undefined. Consider add the operator `?` (optional chaining operator) on `files` property.

2023-07-28 23:11 UTC, ManuelStardust commented on src/pages/search/drawer/landscape/forest/ForestLossPersistenceController.ts
> +          const layersFolder = data.files.dir_png ?? "";
Done

2023-07-31 13:03 UTC, erikasv requested changes

2023-07-31 13:03 UTC, erikasv commented on src/pages/search/SearchContext.tsx
> +  setPolygonValues(areaValue: number, folder?: string): void;
`folder` shouldn't be optional, you are already making it an string always in the FLP controller

2023-07-31 13:03 UTC, erikasv commented on src/pages/search/drawer/landscape/forest/ForestLossPersistenceController.ts
> +  layersFolder?: string;
Same comment as the type in the search context

2023-07-31 20:52 UTC, ManuelStardust commented on src/pages/search/SearchContext.tsx
> +  setPolygonValues(areaValue: number, folder?: string): void;
Done

2023-07-31 20:56 UTC, ManuelStardust commented on src/pages/search/drawer/landscape/forest/ForestLossPersistenceController.ts
> +  layersFolder?: string;
In this case ForestLPData is used as type for response the response of biotablero's backend  and boninabox's backend, however biotablero's backend doesn't return a value for the folder.

2023-07-31 20:56 UTC, ManuelStardust commented on src/pages/search/SearchContext.tsx
> +  setPolygonValues(areaValue: number, folder?: string): void;
Done

2023-07-31 21:55 UTC, erikasv commented on src/pages/search/drawer/landscape/forest/ForestLossPersistenceController.ts
> +  layersFolder?: string;
you're right

2023-07-31 21:55 UTC, erikasv approved these changes

2023-07-31 21:57 UTC, cazapatamar approved these changes

2023-08-01 00:37 UTC, merged