Add modal window
PEM-Humboldt/biotablero-frontend pull request #855
Opened 2023-08-30 07:09 UTC by hacheG

2023-08-30 14:57 UTC, erikasv requested changes
I don't like that when the modal shows up the focus of the page is moved to the top, but when it's closed it moves back down, maybe it has to do something with the modal's style.

2023-08-30 14:57 UTC, erikasv commented on src/app/layout/Footer.jsx
> +import React, {useState} from 'react';
we are currently not enforcing code styles in a programmatic way (we used to), but please follow the [airbnb style guide](https://github.com/airbnb/javascript).

So, for example, add spaces between `{` and `}` from their content, also spaces before and after `=`

2023-08-30 14:57 UTC, erikasv commented on src/app/layout/Footer.jsx
> +const estilo = {
use english please

2023-08-30 14:57 UTC, erikasv commented on src/app/layout/Footer.jsx
> +  const abrirCerrrarModal = () => {
english please

2023-08-30 14:57 UTC, erikasv commented on src/app/layout/Footer.jsx
> +        <h3 style={{position: "absolute", top: "1181px", right: "100px"}}>
Something is odd with the location of the text.
![image](https://github.com/PEM-Humboldt/biotablero-frontend/assets/1734998/3cc88706-0c9b-47ac-a19c-c8c4144130d7)

2023-08-30 15:01 UTC, erikasv commented on src/app/layout/Footer.jsx
> +          <a  href="#" onClick={() => {
use a button and adjust styles

2023-08-30 15:01 UTC, erikasv commented on src/app/layout/Footer.jsx
> +             Cítese
fix indentation

2023-08-30 18:03 UTC, cazapatamar commented
> 

I agree. The behavior seems a bit odd, which is why I'm not particularly fond of the modal. However, if you've already received validation from Cesar, then I'm okay with it.

When i open and close the modal multiple times, the label move up:

![imagen](https://github.com/PEM-Humboldt/biotablero-frontend/assets/19979979/03568fdd-5a1a-4a72-a9ef-15d9356091b8)

2023-08-30 18:04 UTC, cazapatamar commented
> I don't like that when the modal shows up the focus of the page is moved to the top, but when it's closed it moves back down, maybe it has to do something with the modal's style.

> 

I agree. The behavior seems a bit odd, which is why I'm not particularly fond of the modal. However, if you've already received validation from Cesar, then I'm okay with it.

When i open and close the modal multiple times, the label move up:

![imagen](https://github.com/PEM-Humboldt/biotablero-frontend/assets/19979979/03568fdd-5a1a-4a72-a9ef-15d9356091b8)

2023-08-31 21:44 UTC, erikasv requested changes

2023-08-31 21:44 UTC, erikasv commented on src/app/layout/Footer.jsx
> +import { Button, Tooltip, TooltipProps, tooltipClasses, styled } from '@mui/material';
Button is not being used

2023-08-31 21:44 UTC, erikasv commented on src/app/layout/Footer.jsx
> +const LightTooltip = styled(({ className, ...props }: TooltipProps) => (
type annotations only in typescript files

2023-08-31 21:44 UTC, erikasv commented on src/app/layout/Footer.jsx
> +  return(
remove return and go back to previous syntax

2023-08-31 21:44 UTC, erikasv commented on src/app/layout/Footer.jsx
> +          <a href="#" onClick={() => {
change this anchor for a button with different styles, moreover the href `#` moves the focus of the windows to the top

2023-08-31 21:44 UTC, erikasv commented on src/app/layout/Footer.jsx
> +const LightTooltip = styled(({ className, ...props }: TooltipProps) => (
But instead of creating this component with all these hardcoded props, just use the title of the button. See https://github.com/PEM-Humboldt/biotablero-frontend/blob/feature/addQuoteFooter/src/app/Uim.jsx#L72

2023-09-01 17:26 UTC, erikasv requested changes

2023-09-01 17:26 UTC, erikasv commented on src/app/layout/Footer.jsx
> +          <button title='La siguiente citación será copiada al portapapeles: "Instituto de Investigación de Recursos Biológicos Alexander von Humboldt. (2019). BioTablero, cifras e indicadores sobre
put each property in a new line

2023-09-01 17:26 UTC, erikasv commented on src/app/layout/Footer.jsx
> +      <div className="footersm quoteStyle" position="relative">
the property position doesn't seem necessary. And actually it also doesn't seem necessary in the parent

2023-09-01 17:26 UTC, erikasv commented on src/main.css
> +	font-size: 15px !important;
don't use important

2023-09-01 17:26 UTC, erikasv commented on src/app/layout/Footer.jsx
> +            <span>Cítese</span>
why the span? it doesn't seem necessary

2023-09-04 15:15 UTC, erikasv requested changes

2023-09-04 15:15 UTC, erikasv commented on src/app/layout/Footer.jsx
> +  );
fix indentation

2023-09-04 15:15 UTC, erikasv commented on src/app/layout/Footer.jsx
> +              Cítese
fix indentation

2023-09-04 15:15 UTC, erikasv commented on src/main.css
> +footer h3 a, .footersm h3 a{
restore space after `a`

2023-09-04 19:40 UTC, erikasv approved these changes

2023-09-04 19:42 UTC, merged