Hide community momitoring module
PEM-Humboldt/biotablero-frontend pull request #862
Opened 2023-10-03 06:18 UTC by hacheG

2023-10-03 20:50 UTC, erikasv requested changes

2023-10-03 20:50 UTC, erikasv commented on src/app/layout/header/Menu.jsx
> +          {showAlerts && (
oh no, the whole point is to create a new variable, not to reuse the alerts one

2023-10-03 20:50 UTC, erikasv commented on src/pages/home/Content.jsx
> +  if (showAlert) {
same comment as in Menu component.

Also fix indentation

2023-10-03 20:50 UTC, erikasv commented on src/App.jsx
> +            <Route path="/Monitoreo" render={this.loadHome} />
Add a conditional here or in the loadCBMDashboard function, so in develop it still show the CBM module

2023-10-05 16:13 UTC, erikasv requested changes

2023-10-05 16:13 UTC, erikasv commented on src/App.jsx
> +            <Route path="/Monitoreo" render={process.env.REACT_APP_ENVIRONMENT === "develop" ? this.loadCBMDashboard : this.loadHome} />
no, this shouldn't be available based on the env var, but on the feature flag.

2023-10-05 16:13 UTC, erikasv commented on src/app/layout/header/Menu.jsx
> +      .then((value) => this.setState({ showCBMDashboard: value }));
fix indentation

2023-10-05 16:13 UTC, erikasv commented on src/app/layout/header/Menu.jsx
> +          {showCBMDashboard && (
fix inner indentation

2023-10-05 16:13 UTC, erikasv commented on src/pages/home/Content.jsx
> +      .then((value) => setshowCBMDashboard(value));
this should go in the previous useEffect (it doesn't have different conditions)

2023-10-05 20:59 UTC, hacheG commented on src/App.jsx
> +            <Route path="/Monitoreo" render={process.env.REACT_APP_ENVIRONMENT === "develop" ? this.loadCBMDashboard : this.loadHome} />
hola, entiendo lo de no dejar aqui la variable de ambiente, pero me podrias aclarar esta correccion, osea por la correccion anterior sobre este mismo punto se que debo dejar que se pueda acceder a la ruta desde develop pero en esta correccion me podrias por fa explicar un poco mas

2023-10-05 21:26 UTC, erikasv commented on src/App.jsx
> +            <Route path="/Monitoreo" render={process.env.REACT_APP_ENVIRONMENT === "develop" ? this.loadCBMDashboard : this.loadHome} />
tienes que comparar con el valor de la feature flag, no con el de la variable de ambiente

2023-10-05 21:28 UTC, hacheG commented on src/App.jsx
> +            <Route path="/Monitoreo" render={process.env.REACT_APP_ENVIRONMENT === "develop" ? this.loadCBMDashboard : this.loadHome} />
:D graciaaas!!!!

2023-10-09 15:07 UTC, erikasv requested changes

2023-10-09 15:07 UTC, erikasv commented on src/App.jsx
> +  setShowCBMDashboard = isFlagEnabled('CBMModule')
1. setShowCBMDashboard is not being used
2. setState doesn't return anything, setShowCBMDashboard will be a promise that resolves to undefined.
3. The state update must go inside componentDidMount function (if it doesn't exist create it).

the rest of the variables directly declared in the class are functions, this mean they aren't executed until they are needed, in this case setShowCBMDashboard could not have finished before the value of showCBMDashboard is used

2023-10-09 15:07 UTC, erikasv commented on src/App.jsx
> +      this.loadComponent({
undo this indentation

2023-10-09 15:07 UTC, erikasv commented on src/App.jsx
> +            <Route path="/Monitoreo" render={showCBMDashboard ? this.loadCBMDashboard: this.loadHome} />
add space before `:`

2023-10-09 15:07 UTC, erikasv commented on src/app/layout/header/Menu.jsx
> +          {!showAlerts && (
why did you add a negation (`!`)?

2023-10-09 15:07 UTC, erikasv commented on src/app/layout/header/Menu.jsx
> +          {!showCBMDashboard && (
the condition is inverted. Or why the negation(`!`)?

2023-10-09 15:07 UTC, erikasv commented on src/pages/home/Content.jsx
> +  if (!showAlert) {
why the negation?

2023-10-09 15:07 UTC, erikasv commented on src/pages/home/Content.jsx
> +  if (!showCBMDashboard) {
why the negation?

2023-10-10 15:50 UTC, erikasv commented on src/pages/home/Content.jsx
> +console.log("SHOW_ALERT - SHOW_CBM",showAlert, showCBMDashboard);
remove console.log

2023-10-11 14:14 UTC, erikasv approved these changes

2023-10-11 14:19 UTC, merged