Feature/app migrate to hooks and typescript
PEM-Humboldt/biotablero-frontend pull request #875
Opened 2023-11-10 19:49 UTC by hacheG

2023-11-16 16:24 UTC, erikasv requested changes

2023-11-16 16:24 UTC, erikasv commented on src/App.tsx
> +  const [user, setUser] = useState<null>(null);
Also, instead of just null in the type of useState, set the newly defined type as an option

2023-11-16 16:24 UTC, erikasv commented on src/App.tsx
> +  const setUserFunc = (user: null | Response | any): void => setUser(user);
I don't think this function is necessary, try removing it and passing `setUser` directly to Uim

2023-11-16 16:24 UTC, erikasv commented on src/App.tsx
> +      className: "fullgrid",
Home didn't have this class, why did you added it?

2023-11-17 14:31 UTC, erikasv requested changes

2023-11-17 14:31 UTC, erikasv commented on src/App.tsx
> +  const setUserFunc = (user: UserTypes | null) => setUser(user);
I did the change to pass directly setUser and it works. This function is unnecessary.

2023-11-17 14:31 UTC, erikasv commented on src/types/loginUimProps.ts
> +export interface CompanyTypes {
don't export this type

2023-11-21 13:22 UTC, ManuelStardust approved these changes

2023-11-21 14:39 UTC, cazapatamar approved these changes

2023-11-21 15:04 UTC, merged