Feature/short info migrate to hooks and typescript
PEM-Humboldt/biotablero-frontend pull request #882
Opened 2023-11-21 23:12 UTC by hacheG

2023-11-22 16:44 UTC, cazapatamar requested changes

2023-11-22 16:44 UTC, cazapatamar commented on src/components/ShortInfo.tsx
> +// import PropTypes from 'prop-types';
Delete comments

2023-11-22 16:44 UTC, cazapatamar commented on src/components/ShortInfo.tsx
> +// };
Delete comments

2023-11-22 16:44 UTC, cazapatamar commented on src/components/ShortInfo.tsx
> +// };
Include the default values

2023-11-23 00:40 UTC, hacheG commented on src/components/ShortInfo.tsx
> +// import PropTypes from 'prop-types';
ok, I deleted the comments, sorry about that

2023-11-23 00:40 UTC, hacheG commented on src/components/ShortInfo.tsx
> +// };
ok, I deleted the comments, sorry about that

2023-11-23 00:40 UTC, hacheG commented on src/components/ShortInfo.tsx
> +// };
I put "hidden" default value in props className

2023-11-23 01:42 UTC, cazapatamar requested changes

2023-11-23 01:42 UTC, cazapatamar commented on src/components/ShortInfo.jsx
> -  tooltip: '',
You are still missing the default values for `description` and `tooltip` attribute. Remember that an empty string is different to a `null` or `undefined` value.

2023-11-23 02:28 UTC, hacheG commented on src/components/ShortInfo.jsx
> -  tooltip: '',
done

2023-11-23 14:23 UTC, cazapatamar requested changes

2023-11-23 14:23 UTC, cazapatamar commented on src/components/ShortInfo.tsx
> +  collapseButton: boolean;
Why do you only set as non-mandatory the attribute `tootip`?. Previously, no attribute was marked as mandatory.

2023-11-23 14:29 UTC, hacheG commented on src/components/ShortInfo.tsx
> +  collapseButton: boolean;
tooltip var works in home but in ecosystems, for example, it does not have a value

2023-11-23 14:35 UTC, cazapatamar commented on src/components/ShortInfo.tsx
> +  collapseButton: boolean;
Previously, no prop was marked as mandatory. Set the same logic please.

2023-11-23 18:36 UTC, cazapatamar approved these changes

2023-11-23 18:36 UTC, cazapatamar commented
Please dont merge until @ManuelStardust approve

2023-11-23 21:35 UTC, ManuelStardust requested changes

2023-11-23 21:35 UTC, ManuelStardust commented on src/components/ShortInfo.tsx
> +        // eslint-disable-next-line react/no-danger
please delete this comment

2023-11-23 21:40 UTC, hacheG commented on src/components/ShortInfo.tsx
> +        // eslint-disable-next-line react/no-danger
Done!

2023-11-23 21:49 UTC, ManuelStardust approved these changes

2023-11-23 22:32 UTC, cazapatamar approved these changes

2023-11-23 22:33 UTC, merged