Feature/css carousel migrate to hooks and typescript
PEM-Humboldt/biotablero-frontend pull request #888
Opened 2023-12-11 15:19 UTC by hacheG

2023-12-15 14:12 UTC, cazapatamar requested changes

2023-12-15 15:33 UTC, hacheG commented on src/pages/home/content/CssCarousel.tsx
> +}
done

2023-12-15 15:33 UTC, hacheG commented on src/pages/home/content/CssCarousel.tsx
>  /* eslint-env browser */
deleted

2023-12-15 15:54 UTC, cazapatamar requested changes

2023-12-15 15:54 UTC, cazapatamar commented on src/pages/home/content/CssCarousel.tsx
>  }
Please migrate all regular functions to arrow functions

2023-12-15 16:32 UTC, cazapatamar approved these changes

2023-12-15 16:37 UTC, merged

2023-12-23 03:07 UTC, hacheG commented
i did a revert because i found a bug on content component