Add cssCarousel component with typescript
PEM-Humboldt/biotablero-frontend pull request #893
Opened 2023-12-19 16:11 UTC by hacheG

2023-12-21 14:06 UTC, cazapatamar requested changes
After reviewing the PR again, I think these components could be separated into multiple files to make the code more readable and understandable. I suggest separating the 4 components into different files:

- Arrows.tsx: ArrowRigth and ArrowLeft
- Carousel.tsx
- CssCarousel.tsx

What do you think @hacheG?

2023-12-22 19:16 UTC, hacheG commented on src/pages/home/content/CssCarousel.tsx
> +}
i made both changes

2023-12-22 19:17 UTC, hacheG commented on src/pages/home/content/CssCarousel.tsx
>  `;
done

2023-12-22 21:08 UTC, cazapatamar approved these changes

2023-12-23 02:18 UTC, merged