Feature/clean map on polygon
PEM-Humboldt/biotablero-frontend pull request #904
Opened 2024-01-24 16:29 UTC by hacheG

2024-01-26 14:58 UTC, cazapatamar requested changes

2024-01-26 14:58 UTC, cazapatamar commented on src/pages/search/Selector.jsx
>        handlers.areaListChange();
I don't like this approach. 

1) you are calling the function ´areaListChange()´ when de condition is true and false, so in these cases you can simply put it out of the condition.

2) I like better try to inactivate all layers in Search instead of here. Check shutOffLayer funtion and try to use it inside polygonChange handler.

2024-01-26 14:58 UTC, cazapatamar commented on src/pages/search/selector/SearchAreas.jsx
What changes did you make in this file? I couldn't identify them

2024-02-07 17:58 UTC, hacheG commented on src/pages/search/Selector.jsx
>        handlers.areaListChange();
reorganize the code because the "shutOffLayer " function is not executed when clicking the "Área de consulta"  button

2024-02-08 17:02 UTC, erikasv requested changes
Undo the formatting changes, it's impossible to identify the relevant changes

2024-02-09 01:28 UTC, closed without merging

2024-02-09 01:30 UTC, hacheG commented
It was very difficult to review the changes because to a prettier update