Loss persistence layers
PEM-Humboldt/biotablero-frontend pull request #918
Opened 2024-09-30 21:42 UTC by erikasv

## 🛠️ Changes
Send props to MapViewer through SearchContext directly from LossPersistence component

## 🤔 Considerations
- verify the items and collections in the stac server (we had to update them and the last period is missing)

2024-10-28 04:29 UTC, denarch22 commented
Make the adjustment so that it sends category by category to the backend and returns the data in base64

2024-10-29 17:53 UTC, cazapatamar requested changes
Please add an `Associated Issues` section to the PR description and unmark this PR as draft

2024-10-29 17:53 UTC, cazapatamar commented on src/pages/search/drawer/landscape/forest/ForestLossPersistenceController.ts
> +    /** */
Put this TODO in english

2024-10-29 17:53 UTC, cazapatamar commented on src/pages/Search.jsx
> +    this.shutOffLayer(); // Borrar cuando todos los componentes manejen las capas directamente
Add this comment as a TODO (in english)

2024-10-29 20:53 UTC, cazapatamar requested changes

2024-10-29 20:53 UTC, cazapatamar commented on src/pages/Search.jsx
> +    this.shutOffLayer(); // Borrar cuando todos los componentes manejen las capas directamente
And delete the comment in spanish

2024-10-29 22:19 UTC, cazapatamar approved these changes

2024-10-29 22:27 UTC, ManuelStardust approved these changes

2024-10-29 22:38 UTC, merged

2024-12-03 23:30 UTC, erikasv commented on src/pages/search/drawer/landscape/forest/ForestLossPersistenceController.ts
> +  ForestLayerResponse,
este import no se está usando

2024-12-03 23:31 UTC, erikasv commented on src/pages/search/drawer/landscape/forest/ForestLossPersistenceController.ts
> +
Eliminar estas líneas, este proyecto usa prettier para los formatos de los archivos ts

2024-12-03 23:32 UTC, erikasv commented on src/pages/search/drawer/landscape/forest/ForestLossPersistenceController.ts
> +          // Realizar consultas en paralelo para cada categoría basada en el polígono
eliminar comentario

2024-12-03 23:45 UTC, erikasv commented on src/pages/search/drawer/landscape/forest/ForestLossPersistenceController.ts
> +                      idx, // Usar el índice como categoría numérica
esto no es correcto. El orden de los valores en ForestLPKeys es diferente a la numeración asignada en la colección

2024-12-03 23:45 UTC, erikasv commented on src/pages/search/drawer/landscape/forest/ForestLossPersistenceController.ts
> +              const images = response.data.images; // Obtener las imágenes de la respuesta
Cambiar de acuerdo al ajuste que se haga en la tarea [194](https://github.com/PEM-Humboldt/biotablero-scrum/issues/194)

2024-12-03 23:45 UTC, erikasv commented on src/pages/search/drawer/landscape/forest/ForestLossPersistenceController.ts
> +              return Object.entries(images).map(([imageKey, base64Data]) => ({
Toda esta transformación está innecesariamente complicada, después del ajuste de la tarea 194 reimplementar.

2024-12-03 23:45 UTC, erikasv commented on src/pages/search/drawer/landscape/forest/ForestLossPersistenceController.ts
> +          throw new Error("Failed to load polygon-based layer");
Esta no es la forma de manejar los errores aquí, el manejo que se debe dar es con los modales encima del mapa. Dejar el TODO

2024-12-03 23:45 UTC, erikasv commented on src/pages/search/types/forest.ts
> +    images: Record<string, string>;
Esto se debe actualizar con la tarea 194

2025-01-10 19:47 UTC, erikasv commented on src/pages/search/drawer/landscape/forest/ForestLossPersistenceController.ts
> +                      idx, // Usar el índice como categoría numérica
lo correcto era decir que no necesariamente es el mismo, pero en este caso sí lo era, lo mejor igual es mapear cada categoría con su valor numérico explícitamente.